"""Add new column in application logs del_index,del_previous and del_last_index

Revision ID: 000e8310b30e
Revises: 396feff035ce
Create Date: 2026-02-23 08:39:37.494264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000e8310b30e'
down_revision: Union[str, Sequence[str], None] = '396feff035ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_logs', sa.Column('del_index', sa.Integer(), nullable=True))
    op.add_column('application_logs', sa.Column('del_previous', sa.Integer(), nullable=True))
    op.add_column('application_logs', sa.Column('del_last_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_logs', 'del_last_index')
    op.drop_column('application_logs', 'del_previous')
    op.drop_column('application_logs', 'del_index')
    # ### end Alembic commands ###
