"""Add column name is_deleted in notification table

Revision ID: 013243ed604b
Revises: 5b344d97baa1
Create Date: 2026-03-12 09:19:37.632157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013243ed604b'
down_revision: Union[str, Sequence[str], None] = '5b344d97baa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_deleted')
    # ### end Alembic commands ###
