"""add_uuid_to_clinical_trials

Revision ID: 036e6dc08803
Revises: 5f1cc9dbaaa6
Create Date: 2026-09-16 05:59:05.146661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '036e6dc08803'
down_revision: Union[str, Sequence[str], None] = '5f1cc9dbaaa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_trials', sa.Column('uuid', sa.String(length=36), nullable=False))
    op.alter_column('clinical_trials', 'protocol_no',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_clinical_trials_protocol_no'), table_name='clinical_trials')
    op.create_index(op.f('ix_clinical_trials_protocol_no'), 'clinical_trials', ['protocol_no'], unique=False)
    op.create_index(op.f('ix_clinical_trials_uuid'), 'clinical_trials', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_trials_uuid'), table_name='clinical_trials')
    op.drop_index(op.f('ix_clinical_trials_protocol_no'), table_name='clinical_trials')
    op.create_index(op.f('ix_clinical_trials_protocol_no'), 'clinical_trials', ['protocol_no'], unique=True)
    op.alter_column('clinical_trials', 'protocol_no',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('clinical_trials', 'uuid')
    # ### end Alembic commands ###
