"""add new table for payment and OP

Revision ID: 04fcaf9ba74f
Revises: 2a77c1a7a02e
Create Date: 2026-09-22 07:26:33.817805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fcaf9ba74f'
down_revision: Union[str, Sequence[str], None] = '2a77c1a7a02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpr_order_of_payment',
    sa.Column('op_uuid', sa.String(length=36), nullable=False),
    sa.Column('application_uuid', sa.String(length=36), nullable=False),
    sa.Column('parent_op_uuid', sa.String(length=36), nullable=True),
    sa.Column('op_type', sa.String(length=20), nullable=False),
    sa.Column('op_number', sa.String(length=100), nullable=True),
    sa.Column('application_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lrf_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('surcharge', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deficiency_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('issued_by_user_uuid', sa.String(length=36), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_uuid'], ['cpr_application.application_uuid'], ),
    sa.ForeignKeyConstraint(['issued_by_user_uuid'], ['users.user_uuid'], ),
    sa.ForeignKeyConstraint(['parent_op_uuid'], ['cpr_order_of_payment.op_uuid'], ),
    sa.PrimaryKeyConstraint('op_uuid')
    )
    op.create_index(op.f('ix_cpr_order_of_payment_application_uuid'), 'cpr_order_of_payment', ['application_uuid'], unique=False)
    op.create_index(op.f('ix_cpr_order_of_payment_op_number'), 'cpr_order_of_payment', ['op_number'], unique=False)
    op.create_index(op.f('ix_cpr_order_of_payment_op_type'), 'cpr_order_of_payment', ['op_type'], unique=False)
    op.create_index(op.f('ix_cpr_order_of_payment_op_uuid'), 'cpr_order_of_payment', ['op_uuid'], unique=False)
    op.create_index(op.f('ix_cpr_order_of_payment_parent_op_uuid'), 'cpr_order_of_payment', ['parent_op_uuid'], unique=False)
    op.create_index(op.f('ix_cpr_order_of_payment_status'), 'cpr_order_of_payment', ['status'], unique=False)
    op.create_table('cpr_payment_verification',
    sa.Column('verification_uuid', sa.String(length=36), nullable=False),
    sa.Column('op_uuid', sa.String(length=36), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=False),
    sa.Column('type_of_payment', sa.String(length=50), nullable=False),
    sa.Column('official_receipt_number', sa.String(length=100), nullable=False),
    sa.Column('date_of_payment', sa.Date(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('verified_by_user_uuid', sa.String(length=36), nullable=False),
    sa.Column('verified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['op_uuid'], ['cpr_order_of_payment.op_uuid'], ),
    sa.ForeignKeyConstraint(['verified_by_user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('verification_uuid')
    )
    op.create_index(op.f('ix_cpr_payment_verification_official_receipt_number'), 'cpr_payment_verification', ['official_receipt_number'], unique=False)
    op.create_index(op.f('ix_cpr_payment_verification_op_uuid'), 'cpr_payment_verification', ['op_uuid'], unique=False)
    op.create_index(op.f('ix_cpr_payment_verification_reference_number'), 'cpr_payment_verification', ['reference_number'], unique=False)
    op.create_index(op.f('ix_cpr_payment_verification_verification_uuid'), 'cpr_payment_verification', ['verification_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cpr_payment_verification_verification_uuid'), table_name='cpr_payment_verification')
    op.drop_index(op.f('ix_cpr_payment_verification_reference_number'), table_name='cpr_payment_verification')
    op.drop_index(op.f('ix_cpr_payment_verification_op_uuid'), table_name='cpr_payment_verification')
    op.drop_index(op.f('ix_cpr_payment_verification_official_receipt_number'), table_name='cpr_payment_verification')
    op.drop_table('cpr_payment_verification')
    op.drop_index(op.f('ix_cpr_order_of_payment_status'), table_name='cpr_order_of_payment')
    op.drop_index(op.f('ix_cpr_order_of_payment_parent_op_uuid'), table_name='cpr_order_of_payment')
    op.drop_index(op.f('ix_cpr_order_of_payment_op_uuid'), table_name='cpr_order_of_payment')
    op.drop_index(op.f('ix_cpr_order_of_payment_op_type'), table_name='cpr_order_of_payment')
    op.drop_index(op.f('ix_cpr_order_of_payment_op_number'), table_name='cpr_order_of_payment')
    op.drop_index(op.f('ix_cpr_order_of_payment_application_uuid'), table_name='cpr_order_of_payment')
    op.drop_table('cpr_order_of_payment')
    # ### end Alembic commands ###
