"""Add column in CDRR REPORT ,froo and secondary report

Revision ID: 14d59429dd51
Revises: b1c1ea6bdfae
Create Date: 2026-02-16 03:43:16.006756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d59429dd51'
down_revision: Union[str, Sequence[str], None] = 'b1c1ea6bdfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cdrr_reports', sa.Column('category', sa.String(length=100), nullable=True, comment='Category'))
    op.add_column('froo_reports', sa.Column('is_approved', sa.Boolean(), nullable=True, comment='Approved flag'))
    op.add_column('froo_reports', sa.Column('date_extension_approved', sa.Date(), nullable=True, comment='Date extension was approved'))
    op.add_column('froo_reports', sa.Column('status', sa.String(length=100), nullable=True, comment='Status'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('froo_reports', 'status')
    op.drop_column('froo_reports', 'date_extension_approved')
    op.drop_column('froo_reports', 'is_approved')
    op.drop_column('cdrr_reports', 'category')
    # ### end Alembic commands ###
