"""Add director's targeting table

Revision ID: 18a3e0f77b26
Revises: adb7dfef3492
Create Date: 2026-08-04 03:10:32.313183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a3e0f77b26'
down_revision: Union[str, Sequence[str], None] = 'adb7dfef3492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors_target',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_log_id', sa.Integer(), nullable=False),
    sa.Column('main_db_id', sa.Integer(), nullable=False),
    sa.Column('member_user_id', sa.Integer(), nullable=True, comment='Owner of the task at time of targeting'),
    sa.Column('targeted_by_user_id', sa.Integer(), nullable=False, comment='Director/admin who marked this'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('target_start_date', sa.Date(), nullable=True),
    sa.Column('target_end_date', sa.Date(), nullable=True),
    sa.Column('targeted_at', sa.DateTime(), nullable=True),
    sa.Column('untargeted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_log_id'], ['application_logs.id'], ),
    sa.ForeignKeyConstraint(['main_db_id'], ['main_db.DB_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directors_target_application_log_id'), 'directors_target', ['application_log_id'], unique=False)
    op.create_index(op.f('ix_directors_target_is_active'), 'directors_target', ['is_active'], unique=False)
    op.create_index(op.f('ix_directors_target_main_db_id'), 'directors_target', ['main_db_id'], unique=False)
    op.create_index('ix_dt_log_active', 'directors_target', ['application_log_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dt_log_active', table_name='directors_target')
    op.drop_index(op.f('ix_directors_target_main_db_id'), table_name='directors_target')
    op.drop_index(op.f('ix_directors_target_is_active'), table_name='directors_target')
    op.drop_index(op.f('ix_directors_target_application_log_id'), table_name='directors_target')
    op.drop_table('directors_target')
    # ### end Alembic commands ###
