"""Add new column in close table

Revision ID: 1ab4d233164e
Revises: 472ba0ae3f00
Create Date: 2026-06-10 05:33:16.317275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab4d233164e'
down_revision: Union[str, Sequence[str], None] = '472ba0ae3f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('closed_tasks', sa.Column('date_released', sa.DateTime(), nullable=True))
    op.add_column('closed_tasks', sa.Column('type_doc_released', sa.String(length=100), nullable=True))
    op.add_column('closed_tasks', sa.Column('cpr_api_enabled', sa.Boolean(), nullable=True))
    op.add_column('closed_tasks', sa.Column('cpr_insert_success', sa.Boolean(), nullable=True))
    op.add_column('closed_tasks', sa.Column('cpr_insert_error', sa.Text(), nullable=True))
    op.add_column('closed_tasks', sa.Column('cpr_skipped_by_user', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('closed_tasks', 'cpr_skipped_by_user')
    op.drop_column('closed_tasks', 'cpr_insert_error')
    op.drop_column('closed_tasks', 'cpr_insert_success')
    op.drop_column('closed_tasks', 'cpr_api_enabled')
    op.drop_column('closed_tasks', 'type_doc_released')
    op.drop_column('closed_tasks', 'date_released')
    # ### end Alembic commands ###
