"""add index on DB_REG_NO

Revision ID: 1c71f0d01e85
Revises: 74ef20b6b45e
Create Date: 2026-06-30 04:02:17.511376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c71f0d01e85'
down_revision: Union[str, Sequence[str], None] = '74ef20b6b45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_an_reg_no', 'main_db', ['DB_REG_NO'], unique=False, mysql_length=191)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_an_reg_no', table_name='main_db', mysql_length=191)
    # ### end Alembic commands ###
