"""Add folder category 

Revision ID: 280a7e7a0f9e
Revises: 588f72edcdf5
Create Date: 2026-07-02 06:06:46.307868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280a7e7a0f9e'
down_revision: Union[str, Sequence[str], None] = '588f72edcdf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_documents', sa.Column('doc_category', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_application_documents_doc_category'), 'application_documents', ['doc_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_documents_doc_category'), table_name='application_documents')
    op.drop_column('application_documents', 'doc_category')
    # ### end Alembic commands ###
