"""Add subject to main_db

Revision ID: 285bfc0c974e
Revises: 98338bf2ab81
Create Date: 2026-06-01 05:03:31.475674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285bfc0c974e'
down_revision: Union[str, Sequence[str], None] = '98338bf2ab81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_db', sa.Column('DB_SUBJECT', sa.Text(), nullable=True, comment='Subject'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_db', 'DB_SUBJECT')
    # ### end Alembic commands ###
