"""drop_unique_on_ct_ref_no_and_il_approval_no

Revision ID: 2a77c1a7a02e
Revises: 3d857c4d50c0
Create Date: 2026-09-16 06:40:29.627145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a77c1a7a02e'
down_revision: Union[str, Sequence[str], None] = '3d857c4d50c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_trials_ct_ref_no'), table_name='clinical_trials')
    op.create_index(op.f('ix_clinical_trials_ct_ref_no'), 'clinical_trials', ['ct_ref_no'], unique=False)
    op.drop_index(op.f('ix_clinical_trials_il_approval_no'), table_name='clinical_trials')
    op.create_index(op.f('ix_clinical_trials_il_approval_no'), 'clinical_trials', ['il_approval_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_trials_il_approval_no'), table_name='clinical_trials')
    op.create_index(op.f('ix_clinical_trials_il_approval_no'), 'clinical_trials', ['il_approval_no'], unique=True)
    op.drop_index(op.f('ix_clinical_trials_ct_ref_no'), table_name='clinical_trials')
    op.create_index(op.f('ix_clinical_trials_ct_ref_no'), 'clinical_trials', ['ct_ref_no'], unique=True)
    # ### end Alembic commands ###
