"""Add is starred and starred at in application logs

Revision ID: 2c1b2b90054e
Revises: 1ab4d233164e
Create Date: 2026-06-17 01:34:05.073856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c1b2b90054e'
down_revision: Union[str, Sequence[str], None] = '1ab4d233164e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_delegation', 'DB_DATE_DECKED_END',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Date Decked End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_EVAL_END',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Date Evaluation End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_CHECKER_END',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Date Checker End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_SUPERVISOR_END',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Date Supervisor End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_QA_END',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Date QA End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_DIRECTOR_END',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Date Director End',
               existing_nullable=True)
    op.add_column('application_logs', sa.Column('is_starred', sa.SmallInteger(), nullable=False))
    op.add_column('application_logs', sa.Column('starred_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_logs', 'starred_at')
    op.drop_column('application_logs', 'is_starred')
    op.alter_column('application_delegation', 'DB_DATE_DIRECTOR_END',
               existing_type=mysql.DATETIME(),
               comment='Date Director End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_QA_END',
               existing_type=mysql.DATETIME(),
               comment='Date QA End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_SUPERVISOR_END',
               existing_type=mysql.DATETIME(),
               comment='Date Supervisor End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_CHECKER_END',
               existing_type=mysql.DATETIME(),
               comment='Date Checker End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_EVAL_END',
               existing_type=mysql.DATETIME(),
               comment='Date Evaluation End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_DECKED_END',
               existing_type=mysql.DATETIME(),
               comment='Date Decked End',
               existing_nullable=True)
    # ### end Alembic commands ###
