"""add new table cpr table changes

Revision ID: 2da1d9919873
Revises: 04fcaf9ba74f
Create Date: 2026-09-22 08:15:42.812692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da1d9919873'
down_revision: Union[str, Sequence[str], None] = '04fcaf9ba74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpr_table_of_changes',
    sa.Column('change_uuid', sa.String(length=36), nullable=False),
    sa.Column('application_uuid', sa.String(length=36), nullable=False),
    sa.Column('row_order', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('proposed_value', sa.Text(), nullable=True),
    sa.Column('specific_type_of_variation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['application_uuid'], ['cpr_application.application_uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('change_uuid')
    )
    op.create_index(op.f('ix_cpr_table_of_changes_application_uuid'), 'cpr_table_of_changes', ['application_uuid'], unique=False)
    op.create_index(op.f('ix_cpr_table_of_changes_change_uuid'), 'cpr_table_of_changes', ['change_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cpr_table_of_changes_change_uuid'), table_name='cpr_table_of_changes')
    op.drop_index(op.f('ix_cpr_table_of_changes_application_uuid'), table_name='cpr_table_of_changes')
    op.drop_table('cpr_table_of_changes')
    # ### end Alembic commands ###
