"""add analytics indexes

Revision ID: 2e1ded56fbc4
Revises: 6bc70ac32785
Create Date: 2026-05-21 07:43:48.481001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1ded56fbc4'
down_revision: Union[str, Sequence[str], None] = '6bc70ac32785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_an_date_released', 'main_db', ['DB_DATE_RELEASED'], unique=False, mysql_length=10)
    op.create_index('ix_an_distri_country', 'main_db', ['DB_PROD_DISTRI_COUNTRY'], unique=False, mysql_length=100)
    op.create_index('ix_an_importer_country', 'main_db', ['DB_PROD_IMPORTER_COUNTRY'], unique=False, mysql_length=100)
    op.create_index('ix_an_prod_br_name', 'main_db', ['DB_PROD_BR_NAME'], unique=False, mysql_length=191)
    op.create_index('ix_an_prod_class_prescrip', 'main_db', ['DB_PROD_CLASS_PRESCRIP'], unique=False, mysql_length=50)
    op.create_index('ix_an_prod_manu_country', 'main_db', ['DB_PROD_MANU_COUNTRY'], unique=False, mysql_length=100)
    op.create_index('ix_an_repacker_country', 'main_db', ['DB_PROD_REPACKER_COUNTRY'], unique=False, mysql_length=100)
    op.create_index('ix_an_trader_country', 'main_db', ['DB_PROD_TRADER_COUNTRY'], unique=False, mysql_length=100)
    op.create_index('ix_an_type_doc_released', 'main_db', ['DB_TYPE_DOC_RELEASED'], unique=False, mysql_length=20)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_an_type_doc_released', table_name='main_db', mysql_length=20)
    op.drop_index('ix_an_trader_country', table_name='main_db', mysql_length=100)
    op.drop_index('ix_an_repacker_country', table_name='main_db', mysql_length=100)
    op.drop_index('ix_an_prod_manu_country', table_name='main_db', mysql_length=100)
    op.drop_index('ix_an_prod_class_prescrip', table_name='main_db', mysql_length=50)
    op.drop_index('ix_an_prod_br_name', table_name='main_db', mysql_length=191)
    op.drop_index('ix_an_importer_country', table_name='main_db', mysql_length=100)
    op.drop_index('ix_an_distri_country', table_name='main_db', mysql_length=100)
    op.drop_index('ix_an_date_released', table_name='main_db', mysql_length=10)
    # ### end Alembic commands ###
