"""Additional Column in users table (role)

Revision ID: 3a5bc6b9bcaa
Revises: b05fc78a9de2
Create Date: 2026-01-13 15:23:42.577852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3a5bc6b9bcaa'
down_revision: Union[str, Sequence[str], None] = 'b05fc78a9de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('application_logs', 'main_db_dtn',
    #            existing_type=mysql.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=False)
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPERADMIN', name='userrole'), nullable=False))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.alter_column('application_logs', 'main_db_dtn',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
