"""Add new column del_thread in application logs

Revision ID: 3cd598d5f3eb
Revises: 000e8310b30e
Create Date: 2026-02-24 06:16:41.002112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd598d5f3eb'
down_revision: Union[str, Sequence[str], None] = '000e8310b30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_logs', sa.Column('del_thread', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_application_logs_del_thread'), 'application_logs', ['del_thread'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_logs_del_thread'), table_name='application_logs')
    op.drop_column('application_logs', 'del_thread')
    # ### end Alembic commands ###
