"""Add new field audit logs table and column

Revision ID: 3ce6ff595595
Revises: b3b6942a22d4
Create Date: 2026-03-02 04:23:01.420551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce6ff595595'
down_revision: Union[str, Sequence[str], None] = 'b3b6942a22d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_field_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('main_db_id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.String(length=150), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_label', sa.String(length=255), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('step_context', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_field_audit_logs_id'), 'application_field_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_application_field_audit_logs_main_db_id'), 'application_field_audit_logs', ['main_db_id'], unique=False)
    op.create_index(op.f('ix_application_field_audit_logs_session_id'), 'application_field_audit_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_field_audit_logs_session_id'), table_name='application_field_audit_logs')
    op.drop_index(op.f('ix_application_field_audit_logs_main_db_id'), table_name='application_field_audit_logs')
    op.drop_index(op.f('ix_application_field_audit_logs_id'), table_name='application_field_audit_logs')
    op.drop_table('application_field_audit_logs')
    # ### end Alembic commands ###
