"""Update table for upload documents

Revision ID: 40756cadd179
Revises: 280a7e7a0f9e
Create Date: 2026-07-03 15:50:27.254705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '40756cadd179'
down_revision: Union[str, Sequence[str], None] = '280a7e7a0f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_documents', 'main_db_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_documents', 'main_db_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
