"""Add doctrack remark in application logs

Revision ID: 4374e54e7662
Revises: aa9353fa9f99
Create Date: 2026-04-17 21:34:55.480607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4374e54e7662'
down_revision: Union[str, Sequence[str], None] = 'aa9353fa9f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_logs', sa.Column('doctrack_remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_logs', 'doctrack_remarks')
    # ### end Alembic commands ###
