"""Create new table bulk_upload_history_records and bulk_upload_history

Revision ID: 445df3bbea41
Revises: 55630c094fb1
Create Date: 2026-03-06 07:52:19.953506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445df3bbea41'
down_revision: Union[str, Sequence[str], None] = '55630c094fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_upload_history',
    sa.Column('historyID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fileName', sa.String(length=255), nullable=False),
    sa.Column('uploadedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploadedBy', sa.String(length=100), nullable=False),
    sa.Column('insertedCount', sa.Integer(), nullable=False),
    sa.Column('failedCount', sa.Integer(), nullable=False),
    sa.Column('failedRecords', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('historyID')
    )
    op.create_index(op.f('ix_bulk_upload_history_historyID'), 'bulk_upload_history', ['historyID'], unique=False)
    op.create_index(op.f('ix_bulk_upload_history_uploadedBy'), 'bulk_upload_history', ['uploadedBy'], unique=False)
    op.create_table('bulk_upload_history_records',
    sa.Column('recordID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('historyID', sa.Integer(), nullable=False),
    sa.Column('rowNum', sa.Integer(), nullable=False),
    sa.Column('rsn', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['historyID'], ['bulk_upload_history.historyID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recordID')
    )
    op.create_index(op.f('ix_bulk_upload_history_records_historyID'), 'bulk_upload_history_records', ['historyID'], unique=False)
    op.create_index(op.f('ix_bulk_upload_history_records_recordID'), 'bulk_upload_history_records', ['recordID'], unique=False)
    op.create_index(op.f('ix_bulk_upload_history_records_rsn'), 'bulk_upload_history_records', ['rsn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bulk_upload_history_records_rsn'), table_name='bulk_upload_history_records')
    op.drop_index(op.f('ix_bulk_upload_history_records_recordID'), table_name='bulk_upload_history_records')
    op.drop_index(op.f('ix_bulk_upload_history_records_historyID'), table_name='bulk_upload_history_records')
    op.drop_table('bulk_upload_history_records')
    op.drop_index(op.f('ix_bulk_upload_history_uploadedBy'), table_name='bulk_upload_history')
    op.drop_index(op.f('ix_bulk_upload_history_historyID'), table_name='bulk_upload_history')
    op.drop_table('bulk_upload_history')
    # ### end Alembic commands ###
