"""Add new column in main db

Revision ID: 472ba0ae3f00
Revises: 285bfc0c974e
Create Date: 2026-06-01 07:44:52.792747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472ba0ae3f00'
down_revision: Union[str, Sequence[str], None] = '285bfc0c974e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_db', sa.Column('DB_LTR_DATE_RECEIVED_FDAC', sa.Date(), nullable=True, comment='Letter Date Received From FDAC'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_db', 'DB_LTR_DATE_RECEIVED_FDAC')
    # ### end Alembic commands ###
