"""rename evaluator/qa_admin delegation columns, drop qa_supervisor and decker_3

Revision ID: 4bcac14cb44f
Revises: 593b93bd474f
Create Date: 2026-07-27 01:02:03.126323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4bcac14cb44f'
down_revision: Union[str, Sequence[str], None] = '593b93bd474f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmp_delegation', sa.Column('GMP_EVALUATOR', sa.String(length=255), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_EVALUATOR_DECISION', sa.String(length=255), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_EVALUATOR_REMARKS', sa.Text(), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_DATE_EVALUATOR_END', sa.DateTime(), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_QA_ADMIN', sa.String(length=255), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_QA_ADMIN_DECISION', sa.String(length=255), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_QA_ADMIN_REMARKS', sa.Text(), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_DATE_QA_ADMIN_END', sa.DateTime(), nullable=True))
    op.drop_column('gmp_delegation', 'GMP_DECKER_3_REMARKS')
    op.drop_column('gmp_delegation', 'GMP_DECKER_2_REMARKS')
    op.drop_column('gmp_delegation', 'GMP_QA_SUPERVISOR_DECISION')
    op.drop_column('gmp_delegation', 'GMP_DECKER_2_DECISION')
    op.drop_column('gmp_delegation', 'GMP_QA_SUPERVISOR')
    op.drop_column('gmp_delegation', 'GMP_DECKER_3')
    op.drop_column('gmp_delegation', 'GMP_QA_SUPERVISOR_REMARKS')
    op.drop_column('gmp_delegation', 'GMP_QUALITY_EVALUATOR')
    op.drop_column('gmp_delegation', 'GMP_DECKER_3_DECISION')
    op.drop_column('gmp_delegation', 'GMP_DATE_DECKER_2_END')
    op.drop_column('gmp_delegation', 'GMP_QUALITY_EVALUATOR_REMARKS')
    op.drop_column('gmp_delegation', 'GMP_DECKER_2')
    op.drop_column('gmp_delegation', 'GMP_DATE_QA_SUPERVISOR_END')
    op.drop_column('gmp_delegation', 'GMP_QUALITY_EVALUATOR_DECISION')
    op.drop_column('gmp_delegation', 'GMP_DATE_QUALITY_EVALUATOR_END')
    op.drop_column('gmp_delegation', 'GMP_DATE_DECKER_3_END')
    op.alter_column('gmp_record', 'GMP_DATE_RECEIVED',
               existing_type=sa.DATE(),
               comment='Date Received',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_RELEASED_DATE',
               existing_type=sa.DATE(),
               comment='Released Date',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_END_DATE',
               existing_type=sa.DATE(),
               comment='End Date',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_NOD_DATE_1',
               existing_type=sa.DATE(),
               comment='1st Date of NOD',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_NOD_DATE_2',
               existing_type=sa.DATE(),
               comment='2nd Date of NOD',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_NOD_DATE_3',
               existing_type=sa.DATE(),
               comment='3rd Date of NOD',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_NOD_DATE_4',
               existing_type=sa.DATE(),
               comment='4th Date of NOD',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_NOD_DATE_5',
               existing_type=sa.DATE(),
               comment='5th Date of NOD',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_DATE_PRINTED',
               existing_type=sa.DATE(),
               comment='Date Printed',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_COMPLIANCE_DOCS_DATE_RECEIVED',
               existing_type=sa.DATE(),
               comment='Compliance / Additional Docs Date Received',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gmp_record', 'GMP_COMPLIANCE_DOCS_DATE_RECEIVED',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Compliance / Additional Docs Date Received',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_DATE_PRINTED',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date Printed',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_NOD_DATE_5',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='5th Date of NOD',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_NOD_DATE_4',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='4th Date of NOD',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_NOD_DATE_3',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='3rd Date of NOD',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_NOD_DATE_2',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='2nd Date of NOD',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_NOD_DATE_1',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='1st Date of NOD',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_END_DATE',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='End Date',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_RELEASED_DATE',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Released Date',
               existing_nullable=True)
    op.alter_column('gmp_record', 'GMP_DATE_RECEIVED',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date Received',
               existing_nullable=True)
    op.add_column('gmp_delegation', sa.Column('GMP_DATE_DECKER_3_END', mysql.DATETIME(), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_DATE_QUALITY_EVALUATOR_END', mysql.DATETIME(), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_QUALITY_EVALUATOR_DECISION', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_DATE_QA_SUPERVISOR_END', mysql.DATETIME(), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_DECKER_2', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_QUALITY_EVALUATOR_REMARKS', mysql.TEXT(), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_DATE_DECKER_2_END', mysql.DATETIME(), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_DECKER_3_DECISION', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_QUALITY_EVALUATOR', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_QA_SUPERVISOR_REMARKS', mysql.TEXT(), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_DECKER_3', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_QA_SUPERVISOR', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_DECKER_2_DECISION', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_QA_SUPERVISOR_DECISION', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_DECKER_2_REMARKS', mysql.TEXT(), nullable=True))
    op.add_column('gmp_delegation', sa.Column('GMP_DECKER_3_REMARKS', mysql.TEXT(), nullable=True))
    op.drop_column('gmp_delegation', 'GMP_DATE_QA_ADMIN_END')
    op.drop_column('gmp_delegation', 'GMP_QA_ADMIN_REMARKS')
    op.drop_column('gmp_delegation', 'GMP_QA_ADMIN_DECISION')
    op.drop_column('gmp_delegation', 'GMP_QA_ADMIN')
    op.drop_column('gmp_delegation', 'GMP_DATE_EVALUATOR_END')
    op.drop_column('gmp_delegation', 'GMP_EVALUATOR_REMARKS')
    op.drop_column('gmp_delegation', 'GMP_EVALUATOR_DECISION')
    op.drop_column('gmp_delegation', 'GMP_EVALUATOR')
    # ### end Alembic commands ###
