"""add gmp reference no drop dtn unique

Revision ID: 54131bf97b17
Revises: 4bcac14cb44f
Create Date: 2026-07-30 02:10:19.613956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54131bf97b17'
down_revision: Union[str, Sequence[str], None] = '4bcac14cb44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmp_record', sa.Column('GMP_REFERENCE_NO', sa.String(length=50), nullable=True, comment='Reference Number — {DTN}-{sequence}, unique per issuance record'))
    op.drop_index(op.f('ix_gmp_record_GMP_DTN'), table_name='gmp_record')
    op.create_index(op.f('ix_gmp_record_GMP_DTN'), 'gmp_record', ['GMP_DTN'], unique=False)
    op.create_index(op.f('ix_gmp_record_GMP_REFERENCE_NO'), 'gmp_record', ['GMP_REFERENCE_NO'], unique=True)
    # ### end Alembic commands ###

    # ── Manual addition: backfill GMP_REFERENCE_NO for existing records ────
    # Autogenerate only diffs schema, never data — every existing row would
    # otherwise be left with GMP_REFERENCE_NO = NULL. One reference number
    # per existing row, grouped by DTN, ordered by GMP_ID so the earliest
    # record per DTN becomes "-01".
    conn = op.get_bind()
    rows = conn.execute(sa.text(
        "SELECT GMP_ID, GMP_DTN FROM gmp_record WHERE GMP_DTN IS NOT NULL ORDER BY GMP_DTN, GMP_ID"
    )).fetchall()
    seq_by_dtn = {}
    for gmp_id, dtn in rows:
        seq_by_dtn[dtn] = seq_by_dtn.get(dtn, 0) + 1
        ref_no = f"{dtn}-{seq_by_dtn[dtn]:02d}"
        conn.execute(
            sa.text("UPDATE gmp_record SET GMP_REFERENCE_NO = :ref WHERE GMP_ID = :id"),
            {"ref": ref_no, "id": gmp_id},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmp_record_GMP_REFERENCE_NO'), table_name='gmp_record')
    op.drop_index(op.f('ix_gmp_record_GMP_DTN'), table_name='gmp_record')
    op.create_index(op.f('ix_gmp_record_GMP_DTN'), 'gmp_record', ['GMP_DTN'], unique=True)
    op.drop_column('gmp_record', 'GMP_REFERENCE_NO')
    # ### end Alembic commands ###
