"""Update Application Logs, and create new table for notification

Revision ID: 55630c094fb1
Revises: 3ce6ff595595
Create Date: 2026-03-04 03:17:26.071447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55630c094fb1'
down_revision: Union[str, Sequence[str], None] = '3ce6ff595595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link_dtn', sa.String(length=100), nullable=True),
    sa.Column('app_log_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['app_log_id'], ['application_logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_name'), 'notifications', ['user_name'], unique=False)
    op.add_column('application_logs', sa.Column('deadline_date', sa.Date(), nullable=True))
    op.add_column('application_logs', sa.Column('working_days', sa.SmallInteger(), nullable=True))
    op.create_index(op.f('ix_application_logs_deadline_date'), 'application_logs', ['deadline_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_logs_deadline_date'), table_name='application_logs')
    op.drop_column('application_logs', 'working_days')
    op.drop_column('application_logs', 'deadline_date')
    op.drop_index(op.f('ix_notifications_user_name'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
