"""Add new table target assignment

Revision ID: 559e3361eba3
Revises: c64180b7184d
Create Date: 2026-07-14 01:39:47.577121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559e3361eba3'
down_revision: Union[str, Sequence[str], None] = 'c64180b7184d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_log_id', sa.Integer(), nullable=False),
    sa.Column('main_db_id', sa.Integer(), nullable=False),
    sa.Column('member_user_id', sa.Integer(), nullable=False),
    sa.Column('lead_user_id', sa.Integer(), nullable=False),
    sa.Column('lead_assignment_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('targeted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('untargeted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_log_id'], ['application_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_assignment_id'], ['lead_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['main_db_id'], ['main_db.DB_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_log_id', name='uq_target_application_log')
    )
    op.create_index(op.f('ix_target_assignments_application_log_id'), 'target_assignments', ['application_log_id'], unique=False)
    op.create_index(op.f('ix_target_assignments_id'), 'target_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_target_assignments_is_active'), 'target_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_target_assignments_lead_assignment_id'), 'target_assignments', ['lead_assignment_id'], unique=False)
    op.create_index(op.f('ix_target_assignments_lead_user_id'), 'target_assignments', ['lead_user_id'], unique=False)
    op.create_index(op.f('ix_target_assignments_main_db_id'), 'target_assignments', ['main_db_id'], unique=False)
    op.create_index(op.f('ix_target_assignments_member_user_id'), 'target_assignments', ['member_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_assignments_member_user_id'), table_name='target_assignments')
    op.drop_index(op.f('ix_target_assignments_main_db_id'), table_name='target_assignments')
    op.drop_index(op.f('ix_target_assignments_lead_user_id'), table_name='target_assignments')
    op.drop_index(op.f('ix_target_assignments_lead_assignment_id'), table_name='target_assignments')
    op.drop_index(op.f('ix_target_assignments_is_active'), table_name='target_assignments')
    op.drop_index(op.f('ix_target_assignments_id'), table_name='target_assignments')
    op.drop_index(op.f('ix_target_assignments_application_log_id'), table_name='target_assignments')
    op.drop_table('target_assignments')
    # ### end Alembic commands ###
