"""add gmp sent_by tracking fields

Revision ID: 585c63bc9b92
Revises: 6309a0fa31b6
Create Date: 2026-07-15 00:53:57.529898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585c63bc9b92'
down_revision: Union[str, Sequence[str], None] = '6309a0fa31b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmp_application_logs', sa.Column('sent_by_user_id', sa.Integer(), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('sent_by_user_name', sa.String(length=255), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('sent_by_alias', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmp_application_logs', 'sent_by_alias')
    op.drop_column('gmp_application_logs', 'sent_by_user_name')
    op.drop_column('gmp_application_logs', 'sent_by_user_id')
    # ### end Alembic commands ###
