"""Add column in application document

Revision ID: 588f72edcdf5
Revises: 1c71f0d01e85
Create Date: 2026-07-02 03:34:03.685991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588f72edcdf5'
down_revision: Union[str, Sequence[str], None] = '1c71f0d01e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_documents', sa.Column('db_entry_type', sa.String(length=255), nullable=False))
    op.add_column('application_documents', sa.Column('db_dtn', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_application_documents_db_dtn'), 'application_documents', ['db_dtn'], unique=False)
    op.create_index(op.f('ix_application_documents_db_entry_type'), 'application_documents', ['db_entry_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_documents_db_entry_type'), table_name='application_documents')
    op.drop_index(op.f('ix_application_documents_db_dtn'), table_name='application_documents')
    op.drop_column('application_documents', 'db_dtn')
    op.drop_column('application_documents', 'db_entry_type')
    # ### end Alembic commands ###
