"""add donations and donation_change_logs tables

Revision ID: 5965cf95f452
Revises: af993425ec90
Create Date: 2026-09-15 08:08:37.945290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5965cf95f452'
down_revision: Union[str, Sequence[str], None] = 'af993425ec90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_uuid', sa.String(length=36), nullable=False),
    sa.Column('letter_dtn', sa.String(length=50), nullable=True),
    sa.Column('date_received', sa.String(length=50), nullable=True),
    sa.Column('date_received_by_evaluator', sa.String(length=50), nullable=True),
    sa.Column('donor', sa.String(length=255), nullable=True),
    sa.Column('donee', sa.String(length=255), nullable=True),
    sa.Column('registration_dtn', sa.String(length=50), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('packaging', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('batch_lot_no', sa.String(length=255), nullable=True),
    sa.Column('expiration_date', sa.String(length=100), nullable=True),
    sa.Column('total_quantity', sa.String(length=255), nullable=True),
    sa.Column('validity', sa.String(length=100), nullable=True),
    sa.Column('date_issued', sa.String(length=50), nullable=True),
    sa.Column('evaluator', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('donation_reg_no', sa.String(length=50), nullable=True),
    sa.Column('date_forwarded_to_checker', sa.String(length=50), nullable=True),
    sa.Column('date_released', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('upload_by', sa.String(length=150), nullable=True),
    sa.Column('created_by', sa.String(length=150), nullable=True),
    sa.Column('updated_by', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_application_uuid'), 'donations', ['application_uuid'], unique=True)
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    op.create_index(op.f('ix_donations_is_deleted'), 'donations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_donations_letter_dtn'), 'donations', ['letter_dtn'], unique=False)
    op.create_index(op.f('ix_donations_registration_dtn'), 'donations', ['registration_dtn'], unique=False)
    op.create_index(op.f('ix_donations_status'), 'donations', ['status'], unique=False)
    op.create_table('donation_change_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=150), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_donation_change_logs_donation_id', 'donation_change_logs', ['donation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_donation_change_logs_donation_id', table_name='donation_change_logs')
    op.drop_table('donation_change_logs')
    op.drop_index(op.f('ix_donations_status'), table_name='donations')
    op.drop_index(op.f('ix_donations_registration_dtn'), table_name='donations')
    op.drop_index(op.f('ix_donations_letter_dtn'), table_name='donations')
    op.drop_index(op.f('ix_donations_is_deleted'), table_name='donations')
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_application_uuid'), table_name='donations')
    op.drop_table('donations')
    # ### end Alembic commands ###
