"""update clinical trial models

Revision ID: 5f1cc9dbaaa6
Revises: bd20938d6891
Create Date: 2026-09-16 02:51:50.739941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5f1cc9dbaaa6'
down_revision: Union[str, Sequence[str], None] = 'bd20938d6891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinical_trials', 'study_title',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('clinical_trials', 'phase',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('clinical_trials', 'sponsor_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('clinical_trials', 'ip_name',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinical_trials', 'ip_name',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.alter_column('clinical_trials', 'sponsor_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('clinical_trials', 'phase',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('clinical_trials', 'study_title',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
