"""add new table po e-application document

Revision ID: 649b05e11ee8
Revises: cabcfd56e5df
Create Date: 2026-08-25 09:07:50.429853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649b05e11ee8'
down_revision: Union[str, Sequence[str], None] = 'cabcfd56e5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpr_app_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_uuid', sa.String(length=36), nullable=False),
    sa.Column('application_type', sa.String(length=100), nullable=False),
    sa.Column('requirement_group', sa.String(length=20), nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=True),
    sa.Column('requirement_code', sa.String(length=100), nullable=False),
    sa.Column('drive_file_id', sa.String(length=255), nullable=False),
    sa.Column('drive_file_url', sa.Text(), nullable=False),
    sa.Column('drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_name', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_uuid'], ['cpr_application.application_uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpr_app_documents_application_type'), 'cpr_app_documents', ['application_type'], unique=False)
    op.create_index(op.f('ix_cpr_app_documents_application_uuid'), 'cpr_app_documents', ['application_uuid'], unique=False)
    op.create_index(op.f('ix_cpr_app_documents_category_code'), 'cpr_app_documents', ['category_code'], unique=False)
    op.create_index(op.f('ix_cpr_app_documents_id'), 'cpr_app_documents', ['id'], unique=False)
    op.create_index(op.f('ix_cpr_app_documents_requirement_code'), 'cpr_app_documents', ['requirement_code'], unique=False)
    op.create_index(op.f('ix_cpr_app_documents_requirement_group'), 'cpr_app_documents', ['requirement_group'], unique=False)
    op.create_index(op.f('ix_cpr_app_documents_uploaded_by_user_id'), 'cpr_app_documents', ['uploaded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cpr_app_documents_uploaded_by_user_id'), table_name='cpr_app_documents')
    op.drop_index(op.f('ix_cpr_app_documents_requirement_group'), table_name='cpr_app_documents')
    op.drop_index(op.f('ix_cpr_app_documents_requirement_code'), table_name='cpr_app_documents')
    op.drop_index(op.f('ix_cpr_app_documents_id'), table_name='cpr_app_documents')
    op.drop_index(op.f('ix_cpr_app_documents_category_code'), table_name='cpr_app_documents')
    op.drop_index(op.f('ix_cpr_app_documents_application_uuid'), table_name='cpr_app_documents')
    op.drop_index(op.f('ix_cpr_app_documents_application_type'), table_name='cpr_app_documents')
    op.drop_table('cpr_app_documents')
    # ### end Alembic commands ###
