"""Add models for lead assignment

Revision ID: 6bc70ac32785
Revises: af30377b1490
Create Date: 2026-05-09 03:29:25.204424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc70ac32785'
down_revision: Union[str, Sequence[str], None] = 'af30377b1490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_user_id', sa.Integer(), nullable=False),
    sa.Column('member_user_id', sa.Integer(), nullable=False),
    sa.Column('lead_role', sa.String(length=100), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_assignments_id'), 'lead_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_lead_assignments_lead_role'), 'lead_assignments', ['lead_role'], unique=False)
    op.create_index(op.f('ix_lead_assignments_lead_user_id'), 'lead_assignments', ['lead_user_id'], unique=False)
    op.create_index(op.f('ix_lead_assignments_member_user_id'), 'lead_assignments', ['member_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_assignments_member_user_id'), table_name='lead_assignments')
    op.drop_index(op.f('ix_lead_assignments_lead_user_id'), table_name='lead_assignments')
    op.drop_index(op.f('ix_lead_assignments_lead_role'), table_name='lead_assignments')
    op.drop_index(op.f('ix_lead_assignments_id'), table_name='lead_assignments')
    op.drop_table('lead_assignments')
    # ### end Alembic commands ###
