"""add application_documents table

Revision ID: 74ef20b6b45e
Revises: 2c1b2b90054e
Create Date: 2026-06-24 08:20:59.341945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ef20b6b45e'
down_revision: Union[str, Sequence[str], None] = '2c1b2b90054e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('main_db_id', sa.Integer(), nullable=False),
    sa.Column('drive_file_id', sa.String(length=255), nullable=False),
    sa.Column('drive_file_url', sa.Text(), nullable=False),
    sa.Column('drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_name', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['main_db_id'], ['main_db.DB_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_documents_id'), 'application_documents', ['id'], unique=False)
    op.create_index(op.f('ix_application_documents_main_db_id'), 'application_documents', ['main_db_id'], unique=False)
    op.create_index(op.f('ix_application_documents_uploaded_by_user_id'), 'application_documents', ['uploaded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_documents_uploaded_by_user_id'), table_name='application_documents')
    op.drop_index(op.f('ix_application_documents_main_db_id'), table_name='application_documents')
    op.drop_index(op.f('ix_application_documents_id'), table_name='application_documents')
    op.drop_table('application_documents')
    # ### end Alembic commands ###
