"""add new table for clinical trial

Revision ID: 7a4d68d54442
Revises: af993425ec90
Create Date: 2026-09-15 05:52:44.114295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4d68d54442'
down_revision: Union[str, Sequence[str], None] = 'af993425ec90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_trials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol_no', sa.String(length=50), nullable=False),
    sa.Column('study_title', sa.Text(), nullable=False),
    sa.Column('phase', sa.String(length=10), nullable=False),
    sa.Column('sponsor_name', sa.String(length=255), nullable=False),
    sa.Column('sponsor_address', sa.String(length=500), nullable=True),
    sa.Column('sponsor_contact', sa.String(length=255), nullable=True),
    sa.Column('cro_name', sa.String(length=255), nullable=True),
    sa.Column('cro_address', sa.String(length=500), nullable=True),
    sa.Column('cro_contact', sa.String(length=255), nullable=True),
    sa.Column('ct_ref_no', sa.String(length=50), nullable=False),
    sa.Column('ip_name', sa.String(length=500), nullable=False),
    sa.Column('dosage_strength', sa.String(length=100), nullable=True),
    sa.Column('pharma_form', sa.String(length=100), nullable=True),
    sa.Column('drug_type', sa.String(length=100), nullable=True),
    sa.Column('il_approval_no', sa.String(length=50), nullable=False),
    sa.Column('il_approval_date', sa.Date(), nullable=True),
    sa.Column('total_qty_approve', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_trials_ct_ref_no'), 'clinical_trials', ['ct_ref_no'], unique=True)
    op.create_index(op.f('ix_clinical_trials_il_approval_no'), 'clinical_trials', ['il_approval_no'], unique=True)
    op.create_index(op.f('ix_clinical_trials_protocol_no'), 'clinical_trials', ['protocol_no'], unique=True)
    op.create_table('clinical_trial_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinical_trial_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changed_fields', sa.Text(), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clinical_trial_id'], ['clinical_trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_trial_audit_logs_clinical_trial_id'), 'clinical_trial_audit_logs', ['clinical_trial_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_trial_audit_logs_clinical_trial_id'), table_name='clinical_trial_audit_logs')
    op.drop_table('clinical_trial_audit_logs')
    op.drop_index(op.f('ix_clinical_trials_protocol_no'), table_name='clinical_trials')
    op.drop_index(op.f('ix_clinical_trials_il_approval_no'), table_name='clinical_trials')
    op.drop_index(op.f('ix_clinical_trials_ct_ref_no'), table_name='clinical_trials')
    op.drop_table('clinical_trials')
    # ### end Alembic commands ###
