"""add appointment source fields to e_application

Revision ID: 8713a6a97b12
Revises: a7c2e9d41b03
Create Date: 2026-10-07 05:28:04.771133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8713a6a97b12'
down_revision: Union[str, Sequence[str], None] = 'a7c2e9d41b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_application', sa.Column('source_system', sa.String(length=50), nullable=True))
    op.add_column('e_application', sa.Column('source_id', sa.String(length=64), nullable=True))
    op.add_column('e_application', sa.Column('drive_folder_id', sa.String(length=255), nullable=True))
    op.add_column('e_application', sa.Column('drive_link', sa.Text(), nullable=True))
    op.add_column('e_application', sa.Column('form_data', sa.JSON(), nullable=True))
    op.add_column('e_application', sa.Column('worksheet_data', sa.JSON(), nullable=True))
    op.add_column('e_application', sa.Column('files_summary', sa.JSON(), nullable=True))
    op.create_unique_constraint('uq_e_application_reference_number', 'e_application', ['reference_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_e_application_reference_number', 'e_application', type_='unique')
    op.drop_column('e_application', 'files_summary')
    op.drop_column('e_application', 'worksheet_data')
    op.drop_column('e_application', 'form_data')
    op.drop_column('e_application', 'drive_link')
    op.drop_column('e_application', 'drive_folder_id')
    op.drop_column('e_application', 'source_id')
    op.drop_column('e_application', 'source_system')
    # ### end Alembic commands ###
