"""Add new column for re-assignment and re-route and doctrack remarks

Revision ID: 8b44d21fb3dc
Revises: aa9353fa9f99
Create Date: 2026-04-22 02:46:21.276243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b44d21fb3dc'
down_revision: Union[str, Sequence[str], None] = 'aa9353fa9f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_logs', sa.Column('doctrack_remarks', sa.Text(), nullable=True))
    op.add_column('application_logs', sa.Column('reassigned_by_user_id', sa.Integer(), nullable=True))
    op.add_column('application_logs', sa.Column('reassigned_by_user_name', sa.String(length=255), nullable=True))
    op.add_column('application_logs', sa.Column('reassigned_at', sa.DateTime(), nullable=True))
    op.add_column('application_logs', sa.Column('reassigned_from_user_id', sa.Integer(), nullable=True))
    op.add_column('application_logs', sa.Column('reassigned_from_user_name', sa.String(length=255), nullable=True))
    op.add_column('application_logs', sa.Column('reassigned_to_user_id', sa.Integer(), nullable=True))
    op.add_column('application_logs', sa.Column('reassigned_to_user_name', sa.String(length=255), nullable=True))
    op.add_column('application_logs', sa.Column('reassignment_reason', sa.String(length=255), nullable=True))
    op.add_column('application_logs', sa.Column('reassignment_remarks', sa.Text(), nullable=True))
    op.add_column('application_logs', sa.Column('rerouted_by_user_id', sa.Integer(), nullable=True))
    op.add_column('application_logs', sa.Column('rerouted_by_user_name', sa.String(length=255), nullable=True))
    op.add_column('application_logs', sa.Column('rerouted_at', sa.DateTime(), nullable=True))
    op.add_column('application_logs', sa.Column('reroute_from_step', sa.String(length=255), nullable=True))
    op.add_column('application_logs', sa.Column('reroute_target_step', sa.String(length=255), nullable=True))
    op.add_column('application_logs', sa.Column('reroute_reason', sa.String(length=255), nullable=True))
    op.add_column('application_logs', sa.Column('reroute_remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_logs', 'reroute_remarks')
    op.drop_column('application_logs', 'reroute_reason')
    op.drop_column('application_logs', 'reroute_target_step')
    op.drop_column('application_logs', 'reroute_from_step')
    op.drop_column('application_logs', 'rerouted_at')
    op.drop_column('application_logs', 'rerouted_by_user_name')
    op.drop_column('application_logs', 'rerouted_by_user_id')
    op.drop_column('application_logs', 'reassignment_remarks')
    op.drop_column('application_logs', 'reassignment_reason')
    op.drop_column('application_logs', 'reassigned_to_user_name')
    op.drop_column('application_logs', 'reassigned_to_user_id')
    op.drop_column('application_logs', 'reassigned_from_user_name')
    op.drop_column('application_logs', 'reassigned_from_user_id')
    op.drop_column('application_logs', 'reassigned_at')
    op.drop_column('application_logs', 'reassigned_by_user_name')
    op.drop_column('application_logs', 'reassigned_by_user_id')
    op.drop_column('application_logs', 'doctrack_remarks')
    # ### end Alembic commands ###
