"""Add new column received by

Revision ID: 8b8de21c5549
Revises: b1aa04637bca
Create Date: 2026-03-17 03:53:47.271339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8de21c5549'
down_revision: Union[str, Sequence[str], None] = 'b1aa04637bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_logs', sa.Column('is_received', sa.SmallInteger(), nullable=False))
    op.add_column('application_logs', sa.Column('received_at', sa.DateTime(), nullable=True))
    op.add_column('application_logs', sa.Column('received_by', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_logs', 'received_by')
    op.drop_column('application_logs', 'received_at')
    op.drop_column('application_logs', 'is_received')
    # ### end Alembic commands ###
