"""initial main_db + delegation + logs

Revision ID: 963e02cc3f6b
Revises: 
Create Date: 2026-01-16 10:05:41.132081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '963e02cc3f6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('main_db',
    sa.Column('DB_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('DB_DTN', sa.BigInteger(), nullable=True, comment='Document Tracking Number'),
    sa.Column('DB_EST_CAT', sa.String(length=100), nullable=True, comment='Establishment Category'),
    sa.Column('DB_EST_LTO_COMP', sa.Text(), nullable=True, comment='LTO Company Name'),
    sa.Column('DB_EST_LTO_ADD', sa.Text(), nullable=True, comment='LTO Address'),
    sa.Column('DB_EST_EADD', sa.Text(), nullable=True, comment='Email Address'),
    sa.Column('DB_EST_TIN', sa.Text(), nullable=True, comment='Tax Identification Number'),
    sa.Column('DB_EST_CONTACT_NO', sa.Text(), nullable=True, comment='Contact Number'),
    sa.Column('DB_EST_LTO_NO', sa.Text(), nullable=True, comment='LTO Number'),
    sa.Column('DB_EST_VALIDITY', sa.Text(), nullable=True, comment='Validity Period'),
    sa.Column('DB_PROD_BR_NAME', sa.Text(), nullable=True, comment='Brand Name'),
    sa.Column('DB_PROD_GEN_NAME', sa.Text(), nullable=True, comment='Generic Name'),
    sa.Column('DB_PROD_DOS_STR', sa.Text(), nullable=True, comment='Dosage Strength'),
    sa.Column('DB_PROD_DOS_FORM', sa.Text(), nullable=True, comment='Dosage Form'),
    sa.Column('DB_PROD_CLASS_PRESCRIP', sa.Text(), nullable=True, comment='Prescription Classification'),
    sa.Column('DB_PROD_ESS_DRUG_LIST', sa.Text(), nullable=True, comment='Essential Drug List'),
    sa.Column('DB_PROD_PHARMA_CAT', sa.Text(), nullable=True, comment='Pharmaceutical Category'),
    sa.Column('DB_PROD_MANU', sa.Text(), nullable=True, comment='Manufacturer Name'),
    sa.Column('DB_PROD_MANU_ADD', sa.Text(), nullable=True, comment='Manufacturer Address'),
    sa.Column('DB_PROD_MANU_TIN', sa.Text(), nullable=True, comment='Manufacturer TIN'),
    sa.Column('DB_PROD_MANU_LTO_NO', sa.Text(), nullable=True, comment='Manufacturer LTO Number'),
    sa.Column('DB_PROD_MANU_COUNTRY', sa.Text(), nullable=True, comment='Manufacturer Country'),
    sa.Column('DB_PROD_TRADER', sa.Text(), nullable=True, comment='Trader Name'),
    sa.Column('DB_PROD_TRADER_ADD', sa.Text(), nullable=True, comment='Trader Address'),
    sa.Column('DB_PROD_TRADER_TIN', sa.Text(), nullable=True, comment='Trader TIN'),
    sa.Column('DB_PROD_TRADER_LTO_NO', sa.Text(), nullable=True, comment='Trader LTO Number'),
    sa.Column('DB_PROD_TRADER_COUNTRY', sa.Text(), nullable=True, comment='Trader Country'),
    sa.Column('DB_PROD_REPACKER', sa.Text(), nullable=True, comment='Repacker Name'),
    sa.Column('DB_PROD_REPACKER_ADD', sa.Text(), nullable=True, comment='Repacker Address'),
    sa.Column('DB_PROD_REPACKER_TIN', sa.Text(), nullable=True, comment='Repacker TIN'),
    sa.Column('DB_PROD_REPACKER_LTO_NO', sa.Text(), nullable=True, comment='Repacker LTO Number'),
    sa.Column('DB_PROD_REPACKER_COUNTRY', sa.Text(), nullable=True, comment='Repacker Country'),
    sa.Column('DB_PROD_IMPORTER', sa.Text(), nullable=True, comment='Importer Name'),
    sa.Column('DB_PROD_IMPORTER_ADD', sa.Text(), nullable=True, comment='Importer Address'),
    sa.Column('DB_PROD_IMPORTER_TIN', sa.Text(), nullable=True, comment='Importer TIN'),
    sa.Column('DB_PROD_IMPORTER_LTO_NO', sa.Text(), nullable=True, comment='Importer LTO Number'),
    sa.Column('DB_PROD_IMPORTER_COUNTRY', sa.Text(), nullable=True, comment='Importer Country'),
    sa.Column('DB_PROD_DISTRI', sa.Text(), nullable=True, comment='Distributor Name'),
    sa.Column('DB_PROD_DISTRI_ADD', sa.Text(), nullable=True, comment='Distributor Address'),
    sa.Column('DB_PROD_DISTRI_TIN', sa.Text(), nullable=True, comment='Distributor TIN'),
    sa.Column('DB_PROD_DISTRI_LTO_NO', sa.Text(), nullable=True, comment='Distributor LTO Number'),
    sa.Column('DB_PROD_DISTRI_COUNTRY', sa.Text(), nullable=True, comment='Distributor Country'),
    sa.Column('DB_PROD_DISTRI_SHELF_LIFE', sa.Text(), nullable=True, comment='Shelf Life'),
    sa.Column('DB_STORAGE_COND', sa.Text(), nullable=True, comment='Storage Conditions'),
    sa.Column('DB_PACKAGING', sa.Text(), nullable=True, comment='Packaging Details'),
    sa.Column('DB_SUGG_RP', sa.Text(), nullable=True, comment='Suggested Retail Price'),
    sa.Column('DB_NO_SAMPLE', sa.Text(), nullable=True, comment='Number of Samples'),
    sa.Column('DB_EXPIRY_DATE', sa.Text(), nullable=True, comment='Expiry Date'),
    sa.Column('DB_CPR_VALIDITY', sa.Text(), nullable=True, comment='CPR Validity'),
    sa.Column('DB_REG_NO', sa.Text(), nullable=True, comment='Registration Number'),
    sa.Column('DB_APP_TYPE', sa.Text(), nullable=True, comment='Application Type'),
    sa.Column('DB_MOTHER_APP_TYPE', sa.Text(), nullable=True, comment='Mother Application Type'),
    sa.Column('DB_OLD_RSN', sa.Text(), nullable=True, comment='Old RSN'),
    sa.Column('DB_AMMEND1', sa.Text(), nullable=True, comment='Amendment 1'),
    sa.Column('DB_AMMEND2', sa.Text(), nullable=True, comment='Amendment 2'),
    sa.Column('DB_AMMEND3', sa.Text(), nullable=True, comment='Amendment 3'),
    sa.Column('DB_PROD_CAT', sa.Text(), nullable=True, comment='Product Category'),
    sa.Column('DB_CERTIFICATION', sa.Text(), nullable=True, comment='Certification'),
    sa.Column('DB_FEE', sa.Text(), nullable=True, comment='Fee Amount'),
    sa.Column('DB_LRF', sa.Text(), nullable=True, comment='LRF Amount'),
    sa.Column('DB_SURC', sa.Text(), nullable=True, comment='Surcharge Amount'),
    sa.Column('DB_TOTAL', sa.Text(), nullable=True, comment='Total Amount'),
    sa.Column('DB_OR_NO', sa.Text(), nullable=True, comment='Official Receipt Number'),
    sa.Column('DB_DATE_ISSUED', sa.Text(), nullable=True, comment='Date Issued'),
    sa.Column('DB_DATE_RECEIVED_FDAC', sa.Text(), nullable=True, comment='Date Received FDAC'),
    sa.Column('DB_DATE_RECEIVED_CENT', sa.Text(), nullable=True, comment='Date Received Central'),
    sa.Column('DB_MO', sa.Text(), nullable=True, comment='MO'),
    sa.Column('DB_FILE', sa.Text(), nullable=True, comment='File Reference'),
    sa.Column('DB_SECPA', sa.Text(), nullable=True, comment='SECPA'),
    sa.Column('DB_SECPA_EXP_DATE', sa.Text(), nullable=True, comment='SECPA Expiry Date'),
    sa.Column('DB_SECPA_ISSUED_ON', sa.Text(), nullable=True, comment='SECPA Issued Date'),
    sa.Column('DB_DECKING_SCHED', sa.Text(), nullable=True, comment='Decking Schedule'),
    sa.Column('DB_EVAL', sa.Text(), nullable=True, comment='Evaluation'),
    sa.Column('DB_DATE_DECK', sa.Text(), nullable=True, comment='Date Decked'),
    sa.Column('DB_REMARKS_1', sa.Text(), nullable=True, comment='Remarks 1'),
    sa.Column('DB_DATE_REMARKS', sa.Text(), nullable=True, comment='Date of Remarks'),
    sa.Column('DB_CLASS', sa.Text(), nullable=True, comment='Classification'),
    sa.Column('DB_DATE_RELEASED', sa.Text(), nullable=True, comment='Date Released'),
    sa.Column('DB_TYPE_DOC_RELEASED', sa.Text(), nullable=True, comment='Type of Document Released'),
    sa.Column('DB_ATTA_RELEASED', sa.Text(), nullable=True, comment='Attachment Released'),
    sa.Column('DB_CPR_COND', sa.Text(), nullable=True, comment='CPR Condition'),
    sa.Column('DB_CPR_COND_REMARKS', sa.Text(), nullable=True, comment='CPR Condition Remarks'),
    sa.Column('DB_CPR_COND_ADD_REMARKS', sa.Text(), nullable=True, comment='CPR Condition Additional Remarks'),
    sa.Column('DB_APP_STATUS', sa.String(length=50), nullable=True, comment='Application Status'),
    sa.Column('DB_APP_REMARKS', sa.Text(), nullable=True, comment='Application Remarks'),
    sa.Column('DB_TRASH', sa.String(length=50), nullable=True, comment='Trash Status'),
    sa.Column('DB_TRASH_DATE_ENCODED', sa.DateTime(), nullable=True, comment='Trash Date Encoded'),
    sa.Column('DB_USER_UPLOADER', sa.String(length=255), nullable=True, comment='User Uploader'),
    sa.Column('DB_DATE_EXCEL_UPLOAD', sa.DateTime(), nullable=True, comment='Date Excel Uploaded'),
    sa.Column('DB_PHARMA_PROD_CAT', sa.String(length=255), nullable=True, comment='Pharmaceutical Product Category'),
    sa.Column('DB_PHARMA_PROD_CAT_LABEL', sa.String(length=255), nullable=True, comment='Pharmaceutical Product Category Label'),
    sa.Column('DB_IS_IN_PM', mysql.TINYINT(), nullable=True, comment='Is in PM'),
    sa.PrimaryKeyConstraint('DB_ID')
    )
    op.create_index(op.f('ix_main_db_DB_APP_STATUS'), 'main_db', ['DB_APP_STATUS'], unique=False)
    op.create_index(op.f('ix_main_db_DB_DATE_EXCEL_UPLOAD'), 'main_db', ['DB_DATE_EXCEL_UPLOAD'], unique=False)
    op.create_index(op.f('ix_main_db_DB_DTN'), 'main_db', ['DB_DTN'], unique=True)
    op.create_index(op.f('ix_main_db_DB_EST_CAT'), 'main_db', ['DB_EST_CAT'], unique=False)
    op.create_index(op.f('ix_main_db_DB_ID'), 'main_db', ['DB_ID'], unique=False)
    op.create_table('application_delegation',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('DB_MAIN_ID', sa.Integer(), nullable=False, comment='FK to MainDB'),
    sa.Column('DB_DECKER', sa.Text(), nullable=True, comment='Decker Name'),
    sa.Column('DB_DECKER_DECISION', sa.Text(), nullable=True, comment='Decker Decision'),
    sa.Column('DB_DECKER_REMARKS', sa.Text(), nullable=True, comment='Decker Remarks'),
    sa.Column('DB_DATE_DECKED_END', sa.Text(), nullable=True, comment='Date Decked End'),
    sa.Column('DB_EVALUATOR', sa.Text(), nullable=True, comment='Evaluator Name'),
    sa.Column('DB_EVAL_DECISION', sa.Text(), nullable=True, comment='Evaluator Decision'),
    sa.Column('DB_EVAL_REMARKS', sa.Text(), nullable=True, comment='Evaluator Remarks'),
    sa.Column('DB_DATE_EVAL_END', sa.Text(), nullable=True, comment='Date Evaluation End'),
    sa.Column('DB_CHECKER', sa.Text(), nullable=True, comment='Checker Name'),
    sa.Column('DB_CHECKER_DECISION', sa.Text(), nullable=True, comment='Checker Decision'),
    sa.Column('DB_CHECKER_REMARKS', sa.Text(), nullable=True, comment='Checker Remarks'),
    sa.Column('DB_DATE_CHECKER_END', sa.Text(), nullable=True, comment='Date Checker End'),
    sa.Column('DB_SUPERVISOR', sa.Text(), nullable=True, comment='Supervisor Name'),
    sa.Column('DB_SUPERVISOR_DECISION', sa.Text(), nullable=True, comment='Supervisor Decision'),
    sa.Column('DB_SUPERVISOR_REMARKS', sa.Text(), nullable=True, comment='Supervisor Remarks'),
    sa.Column('DB_DATE_SUPERVISOR_END', sa.Text(), nullable=True, comment='Date Supervisor End'),
    sa.Column('DB_QA', sa.Text(), nullable=True, comment='QA Name'),
    sa.Column('DB_QA_DECISION', sa.Text(), nullable=True, comment='QA Decision'),
    sa.Column('DB_QA_REMARKS', sa.Text(), nullable=True, comment='QA Remarks'),
    sa.Column('DB_DATE_QA_END', sa.Text(), nullable=True, comment='Date QA End'),
    sa.Column('DB_DIRECTOR', sa.Text(), nullable=True, comment='Director Name'),
    sa.Column('DB_DIRECTOR_DECISION', sa.Text(), nullable=True, comment='Director Decision'),
    sa.Column('DB_DIRECTOR_REMARKS', sa.Text(), nullable=True, comment='Director Remarks'),
    sa.Column('DB_DATE_DIRECTOR_END', sa.Text(), nullable=True, comment='Date Director End'),
    sa.ForeignKeyConstraint(['DB_MAIN_ID'], ['main_db.DB_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_application_delegation_DB_MAIN_ID'), 'application_delegation', ['DB_MAIN_ID'], unique=True)
    op.create_table('application_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('main_db_id', sa.Integer(), nullable=False),
    sa.Column('application_step', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('application_status', sa.String(length=255), nullable=True),
    sa.Column('application_decision', sa.String(length=255), nullable=True),
    sa.Column('application_remarks', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('accomplished_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['main_db_id'], ['main_db.DB_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_logs_application_status'), 'application_logs', ['application_status'], unique=False)
    op.create_index(op.f('ix_application_logs_id'), 'application_logs', ['id'], unique=False)
    op.create_index(op.f('ix_application_logs_main_db_id'), 'application_logs', ['main_db_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPERADMIN', name='userrole'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_application_logs_main_db_id'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_id'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_application_status'), table_name='application_logs')
    op.drop_table('application_logs')
    op.drop_index(op.f('ix_application_delegation_DB_MAIN_ID'), table_name='application_delegation')
    op.drop_table('application_delegation')
    op.drop_index(op.f('ix_main_db_DB_ID'), table_name='main_db')
    op.drop_index(op.f('ix_main_db_DB_EST_CAT'), table_name='main_db')
    op.drop_index(op.f('ix_main_db_DB_DTN'), table_name='main_db')
    op.drop_index(op.f('ix_main_db_DB_DATE_EXCEL_UPLOAD'), table_name='main_db')
    op.drop_index(op.f('ix_main_db_DB_APP_STATUS'), table_name='main_db')
    op.drop_table('main_db')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
