"""Add new column in users table

Revision ID: 98338bf2ab81
Revises: f088d6f232f8
Create Date: 2026-05-29 15:58:47.990221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '98338bf2ab81'
down_revision: Union[str, Sequence[str], None] = 'f088d6f232f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_upload_history', mysql.TINYINT(display_width=1), nullable=False, comment='Show upload history on dashboard'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_upload_history')
    # ### end Alembic commands ###
