"""Update dates in application delegation

Revision ID: 992c33bb65c1
Revises: 963e02cc3f6b
Create Date: 2026-01-16 15:52:35.325303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '992c33bb65c1'
down_revision: Union[str, Sequence[str], None] = '963e02cc3f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_delegation', 'DB_DATE_DECKED_END',
               existing_type=mysql.TEXT(),
               type_=sa.DateTime(),
               existing_comment='Date Decked End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_EVAL_END',
               existing_type=mysql.TEXT(),
               type_=sa.DateTime(),
               existing_comment='Date Evaluation End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_CHECKER_END',
               existing_type=mysql.TEXT(),
               type_=sa.DateTime(),
               existing_comment='Date Checker End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_SUPERVISOR_END',
               existing_type=mysql.TEXT(),
               type_=sa.DateTime(),
               existing_comment='Date Supervisor End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_QA_END',
               existing_type=mysql.TEXT(),
               type_=sa.DateTime(),
               existing_comment='Date QA End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_DIRECTOR_END',
               existing_type=mysql.TEXT(),
               type_=sa.DateTime(),
               existing_comment='Date Director End',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_delegation', 'DB_DATE_DIRECTOR_END',
               existing_type=sa.DateTime(),
               type_=mysql.TEXT(),
               existing_comment='Date Director End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_QA_END',
               existing_type=sa.DateTime(),
               type_=mysql.TEXT(),
               existing_comment='Date QA End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_SUPERVISOR_END',
               existing_type=sa.DateTime(),
               type_=mysql.TEXT(),
               existing_comment='Date Supervisor End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_CHECKER_END',
               existing_type=sa.DateTime(),
               type_=mysql.TEXT(),
               existing_comment='Date Checker End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_EVAL_END',
               existing_type=sa.DateTime(),
               type_=mysql.TEXT(),
               existing_comment='Date Evaluation End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_DECKED_END',
               existing_type=sa.DateTime(),
               type_=mysql.TEXT(),
               existing_comment='Date Decked End',
               existing_nullable=True)
    # ### end Alembic commands ###
