"""Update application delegation table column

Revision ID: a42d7a8d8ecd
Revises: f6d41b7d72dc
Create Date: 2026-02-09 07:21:30.520192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a42d7a8d8ecd'
down_revision: Union[str, Sequence[str], None] = 'f6d41b7d72dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_delegation', sa.Column('DB_DATE_RELEASING_OFFICER_END', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('application_delegation', 'DB_RELEASING_OFFICER_END')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_delegation', sa.Column('DB_RELEASING_OFFICER_END', mysql.DATETIME(), nullable=True))
    op.drop_column('application_delegation', 'DB_DATE_RELEASING_OFFICER_END')
    # ### end Alembic commands ###
