"""add decision authority fields to application_logs

Revision ID: aa9353fa9f99
Revises: b1aa04637bca
Create Date: 2026-04-15 05:54:49.633011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9353fa9f99'
down_revision: Union[str, Sequence[str], None] = 'b1aa04637bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('application_logs', sa.Column('action_type', sa.String(length=100), nullable=True))
    op.add_column('application_logs', sa.Column('decision_result', sa.String(length=255), nullable=True))
    op.add_column('application_logs', sa.Column('decision_authority_id', sa.Integer(), nullable=True))
    op.add_column('application_logs', sa.Column('decision_authority_name', sa.String(length=255), nullable=True))
    op.add_column('application_logs', sa.Column('is_received', sa.SmallInteger(), nullable=False))
    op.add_column('application_logs', sa.Column('received_at', sa.DateTime(), nullable=True))
    op.add_column('application_logs', sa.Column('received_by', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_application_logs_action_type'), 'application_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_application_logs_decision_authority_id'), 'application_logs', ['decision_authority_id'], unique=False)
    op.create_index(op.f('ix_application_logs_decision_result'), 'application_logs', ['decision_result'], unique=False)
    op.create_index(op.f('ix_application_logs_user_id'), 'application_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'application_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'application_logs', 'main_db', ['main_db_id'], ['DB_ID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'application_logs', 'users', ['decision_authority_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application_logs', type_='foreignkey')
    op.drop_constraint(None, 'application_logs', type_='foreignkey')
    op.drop_constraint(None, 'application_logs', type_='foreignkey')
    op.drop_index(op.f('ix_application_logs_user_id'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_decision_result'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_decision_authority_id'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_action_type'), table_name='application_logs')
    op.drop_column('application_logs', 'received_by')
    op.drop_column('application_logs', 'received_at')
    op.drop_column('application_logs', 'is_received')
    op.drop_column('application_logs', 'decision_authority_name')
    op.drop_column('application_logs', 'decision_authority_id')
    op.drop_column('application_logs', 'decision_result')
    op.drop_column('application_logs', 'action_type')
    op.drop_column('application_logs', 'user_id')
    # ### end Alembic commands ###
