"""add profile picture fields to users

Revision ID: adb7dfef3492
Revises: fe7c06bcd3be
Create Date: 2026-07-23 09:42:45.603541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb7dfef3492'
down_revision: Union[str, Sequence[str], None] = 'fe7c06bcd3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('profile_picture_drive_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_drive_id')
    op.drop_column('users', 'profile_picture_url')
    # ### end Alembic commands ###
