"""Add closed_tasks table

Revision ID: af30377b1490
Revises: bbc9bf306156
Create Date: 2026-05-08 03:18:11.295775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af30377b1490'
down_revision: Union[str, Sequence[str], None] = 'bbc9bf306156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closed_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('main_db_id', sa.Integer(), nullable=False),
    sa.Column('app_log_id', sa.Integer(), nullable=True),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('closed_by_user_name', sa.String(length=255), nullable=False),
    sa.Column('reason_for_closing', sa.String(length=255), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_log_id'], ['application_logs.id'], ),
    sa.ForeignKeyConstraint(['main_db_id'], ['main_db.DB_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closed_tasks_id'), 'closed_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_closed_tasks_main_db_id'), 'closed_tasks', ['main_db_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_closed_tasks_main_db_id'), table_name='closed_tasks')
    op.drop_index(op.f('ix_closed_tasks_id'), table_name='closed_tasks')
    op.drop_table('closed_tasks')
    # ### end Alembic commands ###
