"""Add Column in application log for read tracking

Revision ID: b1aa04637bca
Revises: 013243ed604b
Create Date: 2026-03-16 02:32:50.821305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1aa04637bca'
down_revision: Union[str, Sequence[str], None] = '013243ed604b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_logs', sa.Column('is_read', sa.SmallInteger(), nullable=False))
    op.add_column('application_logs', sa.Column('read_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_logs', 'read_at')
    op.drop_column('application_logs', 'is_read')
    # ### end Alembic commands ###
