"""Additional Table for cdrr and froo

Revision ID: b1c1ea6bdfae
Revises: a42d7a8d8ecd
Create Date: 2026-02-12 07:17:03.720671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c1ea6bdfae'
down_revision: Union[str, Sequence[str], None] = 'a42d7a8d8ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdrr_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_received_by_center', sa.Date(), nullable=True, comment='Date received by center'),
    sa.Column('date_decked', sa.Date(), nullable=True, comment='Date decked'),
    sa.Column('dtn', sa.String(length=100), nullable=True, comment='DTN number'),
    sa.Column('name_of_importer', sa.String(length=255), nullable=True, comment='Name of importer'),
    sa.Column('lto_number', sa.String(length=100), nullable=True, comment='LTO number'),
    sa.Column('address', sa.Text(), nullable=True, comment='Address'),
    sa.Column('type_of_application', sa.String(length=100), nullable=True, comment='Type of application'),
    sa.Column('evaluator', sa.String(length=255), nullable=True, comment='Evaluator name'),
    sa.Column('date_evaluated', sa.Date(), nullable=True, comment='Date evaluated'),
    sa.Column('name_of_foreign_manufacturer', sa.String(length=255), nullable=True, comment='Foreign manufacturer name'),
    sa.Column('plant_address', sa.Text(), nullable=True, comment='Plant address'),
    sa.Column('secpa_number', sa.String(length=100), nullable=True, comment='SECPA number'),
    sa.Column('certificate_number', sa.String(length=100), nullable=True, comment='Certificate number'),
    sa.Column('date_of_issuance', sa.Date(), nullable=True, comment='Date of issuance'),
    sa.Column('type_of_issuance', sa.String(length=100), nullable=True, comment='Type of issuance'),
    sa.Column('product_line', sa.String(length=255), nullable=True, comment='Product line'),
    sa.Column('certificate_validity', sa.Date(), nullable=True, comment='Certificate validity date'),
    sa.Column('status', sa.String(length=100), nullable=True, comment='Status'),
    sa.Column('released_date', sa.Date(), nullable=True, comment='Released date'),
    sa.Column('overall_deadline', sa.Date(), nullable=True, comment='Overall deadline (60 days)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='Soft delete flag'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cdrr_reports_dtn'), 'cdrr_reports', ['dtn'], unique=False)
    op.create_index(op.f('ix_cdrr_reports_id'), 'cdrr_reports', ['id'], unique=False)
    op.create_table('cdrr_secondary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cdrr_report_id', sa.Integer(), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=True, comment='Date received (CDRR)'),
    sa.Column('secpa_number', sa.String(length=100), nullable=True, comment='SECPA number'),
    sa.Column('certificate_number', sa.String(length=100), nullable=True, comment='Certificate number'),
    sa.Column('date_of_issuance', sa.Date(), nullable=True, comment='Date of issuance'),
    sa.Column('type_of_issuance', sa.String(length=100), nullable=True, comment='Type of issuance'),
    sa.Column('product_line', sa.String(length=255), nullable=True, comment='Product line'),
    sa.Column('certificate_validity', sa.Date(), nullable=True, comment='Certificate validity'),
    sa.Column('status', sa.String(length=100), nullable=True, comment='Status'),
    sa.Column('released_date', sa.Date(), nullable=True, comment='Released date'),
    sa.Column('overall_deadline', sa.Date(), nullable=True, comment='Overall deadline 60 days'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='Soft delete flag'),
    sa.ForeignKeyConstraint(['cdrr_report_id'], ['cdrr_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cdrr_secondary_cdrr_report_id'), 'cdrr_secondary', ['cdrr_report_id'], unique=True)
    op.create_index(op.f('ix_cdrr_secondary_id'), 'cdrr_secondary', ['id'], unique=False)
    op.create_table('froo_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cdrr_report_id', sa.Integer(), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=True, comment='Date received by FROO'),
    sa.Column('date_inspected', sa.Date(), nullable=True, comment='Date inspected'),
    sa.Column('date_endorsed_to_cdrr', sa.Date(), nullable=True, comment='Date endorsed to CDRR (COC/RL)'),
    sa.Column('overall_deadline', sa.Date(), nullable=True, comment='FROO overall deadline'),
    sa.Column('approved_extension', sa.Date(), nullable=True, comment='Approved extension (3 months)'),
    sa.Column('new_overall_deadline', sa.Date(), nullable=True, comment='New overall deadline after extension'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='Soft delete flag'),
    sa.ForeignKeyConstraint(['cdrr_report_id'], ['cdrr_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_froo_reports_cdrr_report_id'), 'froo_reports', ['cdrr_report_id'], unique=True)
    op.create_index(op.f('ix_froo_reports_id'), 'froo_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_froo_reports_id'), table_name='froo_reports')
    op.drop_index(op.f('ix_froo_reports_cdrr_report_id'), table_name='froo_reports')
    op.drop_table('froo_reports')
    op.drop_index(op.f('ix_cdrr_secondary_id'), table_name='cdrr_secondary')
    op.drop_index(op.f('ix_cdrr_secondary_cdrr_report_id'), table_name='cdrr_secondary')
    op.drop_table('cdrr_secondary')
    op.drop_index(op.f('ix_cdrr_reports_id'), table_name='cdrr_reports')
    op.drop_index(op.f('ix_cdrr_reports_dtn'), table_name='cdrr_reports')
    op.drop_table('cdrr_reports')
    # ### end Alembic commands ###
