"""Add new column named DB_PROCESSING_TYPE in main_db

Revision ID: b3b6942a22d4
Revises: 3cd598d5f3eb
Create Date: 2026-02-26 02:33:53.945944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b6942a22d4'
down_revision: Union[str, Sequence[str], None] = '3cd598d5f3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_db', sa.Column('DB_PROCESSING_TYPE', sa.Text(), nullable=True, comment='Processing Type'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_db', 'DB_PROCESSING_TYPE')
    # ### end Alembic commands ###
