"""add task tracking fields to application_logs

Revision ID: b45a50220706
Revises: ab2d4171a928
Create Date: 2026-09-04 07:53:24.105199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45a50220706'
down_revision: Union[str, Sequence[str], None] = 'ab2d4171a928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_logs', sa.Column('added_by_user_id', sa.Integer(), nullable=True))
    op.add_column('application_logs', sa.Column('added_by_user_name', sa.String(length=255), nullable=True))
    op.add_column('application_logs', sa.Column('added_at', sa.DateTime(), nullable=True))
    op.add_column('application_logs', sa.Column('add_task_remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_logs', 'add_task_remarks')
    op.drop_column('application_logs', 'added_at')
    op.drop_column('application_logs', 'added_by_user_name')
    op.drop_column('application_logs', 'added_by_user_id')
    # ### end Alembic commands ###
