"""add gmp tables

Revision ID: baeecbcab1cc
Revises: 2c1b2b90054e
Create Date: 2026-07-06 00:43:18.564960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'baeecbcab1cc'
down_revision: Union[str, Sequence[str], None] = '2c1b2b90054e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmp_record',
    sa.Column('GMP_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('GMP_DTN', sa.BigInteger(), nullable=True, comment='Document Tracking Number'),
    sa.Column('GMP_RELATED_DTN', sa.Text(), nullable=True, comment='Related / Mother DTN'),
    sa.Column('GMP_DATE_RECEIVED', sa.Text(), nullable=True, comment='Date Received'),
    sa.Column('GMP_LTO_COMPANY', sa.Text(), nullable=True, comment='Name of Establishment'),
    sa.Column('GMP_LTO_NUMBER', sa.Text(), nullable=True, comment='LTO Number'),
    sa.Column('GMP_LTO_ADDRESS', sa.Text(), nullable=True, comment='Address'),
    sa.Column('GMP_TRANSACTION_TYPE', sa.Text(), nullable=True, comment='Transaction Type'),
    sa.Column('GMP_EST_CATEGORY', sa.String(length=100), nullable=True, comment='Category'),
    sa.Column('GMP_FOREIGN_MANUFACTURER', sa.Text(), nullable=True, comment='Foreign Manufacturer'),
    sa.Column('GMP_FOREIGN_MANUFACTURER_ADDRESS', sa.Text(), nullable=True, comment='Foreign Manufacturer Address'),
    sa.Column('GMP_SECPA_NUMBER', sa.Text(), nullable=True, comment='SECPA Number'),
    sa.Column('GMP_CERTIFICATE_NUMBER', sa.Text(), nullable=True, comment='Certificate Number'),
    sa.Column('GMP_TYPE_OF_ISSUANCE', sa.Text(), nullable=True, comment='Type of Issuance'),
    sa.Column('GMP_CERTIFICATE_VALIDITY', sa.Text(), nullable=True, comment='Certificate Validity'),
    sa.Column('GMP_DECISION', sa.Text(), nullable=True, comment='Decision'),
    sa.Column('GMP_APP_STATUS', sa.String(length=50), nullable=True, comment='Status'),
    sa.Column('GMP_RELEASED_DATE', sa.Text(), nullable=True, comment='Released Date'),
    sa.Column('GMP_PROCESSED_TIME', sa.Text(), nullable=True, comment='Processed Time'),
    sa.Column('GMP_END_DATE', sa.Text(), nullable=True, comment='End Date'),
    sa.Column('GMP_TIMELINE', sa.Text(), nullable=True, comment='Timeline'),
    sa.Column('GMP_REMARKS', sa.Text(), nullable=True, comment='Remarks'),
    sa.Column('GMP_NOD_DATE_1', sa.Text(), nullable=True, comment='1st Date of NOD'),
    sa.Column('GMP_NOD_DATE_2', sa.Text(), nullable=True, comment='2nd Date of NOD'),
    sa.Column('GMP_NOD_DATE_3', sa.Text(), nullable=True, comment='3rd Date of NOD'),
    sa.Column('GMP_NOD_DATE_4', sa.Text(), nullable=True, comment='4th Date of NOD'),
    sa.Column('GMP_NOD_DATE_5', sa.Text(), nullable=True, comment='5th Date of NOD'),
    sa.Column('GMP_DATE_PRINTED', sa.Text(), nullable=True, comment='Date Printed'),
    sa.Column('GMP_COMPLIANCE_DOCS_DATE_RECEIVED', sa.Text(), nullable=True, comment='Compliance / Additional Docs Date Received'),
    sa.Column('GMP_PRODUCT_LINE', sa.String(length=100), nullable=True, comment='Product Line'),
    sa.Column('GMP_CURRENT_STEP', sa.String(length=100), nullable=True, comment='Current Workflow Step'),
    sa.Column('GMP_EVALUATOR', sa.Text(), nullable=True, comment='Assigned Evaluator'),
    sa.Column('GMP_PICS_NONPICS', sa.String(length=50), nullable=True, comment='PIC/S or NON PIC/S'),
    sa.Column('GMP_TRASH', sa.String(length=50), nullable=True, comment='Trash Status'),
    sa.Column('GMP_TRASH_DATE_ENCODED', sa.DateTime(), nullable=True, comment='Trash Date Encoded'),
    sa.Column('GMP_USER_UPLOADER', sa.String(length=255), nullable=True, comment='User Uploader'),
    sa.Column('GMP_DATE_EXCEL_UPLOAD', sa.DateTime(), nullable=True, comment='Date Excel Uploaded'),
    sa.PrimaryKeyConstraint('GMP_ID')
    )
    op.create_index('ix_gmp_lto_company', 'gmp_record', ['GMP_LTO_COMPANY'], unique=False, mysql_length=191)
    op.create_index(op.f('ix_gmp_record_GMP_APP_STATUS'), 'gmp_record', ['GMP_APP_STATUS'], unique=False)
    op.create_index(op.f('ix_gmp_record_GMP_CURRENT_STEP'), 'gmp_record', ['GMP_CURRENT_STEP'], unique=False)
    op.create_index(op.f('ix_gmp_record_GMP_DATE_EXCEL_UPLOAD'), 'gmp_record', ['GMP_DATE_EXCEL_UPLOAD'], unique=False)
    op.create_index(op.f('ix_gmp_record_GMP_DTN'), 'gmp_record', ['GMP_DTN'], unique=True)
    op.create_index(op.f('ix_gmp_record_GMP_EST_CATEGORY'), 'gmp_record', ['GMP_EST_CATEGORY'], unique=False)
    op.create_index(op.f('ix_gmp_record_GMP_ID'), 'gmp_record', ['GMP_ID'], unique=False)
    op.create_index(op.f('ix_gmp_record_GMP_PICS_NONPICS'), 'gmp_record', ['GMP_PICS_NONPICS'], unique=False)
    op.create_index(op.f('ix_gmp_record_GMP_PRODUCT_LINE'), 'gmp_record', ['GMP_PRODUCT_LINE'], unique=False)
    op.create_index('ix_gmp_transaction_type', 'gmp_record', ['GMP_TRANSACTION_TYPE'], unique=False, mysql_length=50)
    op.create_index('ix_gmp_type_of_issuance', 'gmp_record', ['GMP_TYPE_OF_ISSUANCE'], unique=False, mysql_length=50)
    op.create_table('gmp_application_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gmp_record_id', sa.Integer(), nullable=False),
    sa.Column('application_step', sa.String(length=100), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('application_status', sa.String(length=50), nullable=True),
    sa.Column('application_decision', sa.Text(), nullable=True),
    sa.Column('application_remarks', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('accomplished_date', sa.DateTime(), nullable=True),
    sa.Column('del_index', sa.Integer(), nullable=True),
    sa.Column('del_previous', sa.Integer(), nullable=True),
    sa.Column('del_last_index', sa.Integer(), nullable=True),
    sa.Column('del_thread', sa.String(length=20), nullable=True),
    sa.Column('is_read', mysql.TINYINT(), nullable=False),
    sa.Column('is_starred', mysql.TINYINT(), nullable=False),
    sa.Column('starred_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('received_by', sa.String(length=255), nullable=True),
    sa.Column('is_received', mysql.TINYINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gmp_record_id'], ['gmp_record.GMP_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmp_application_logs_application_step'), 'gmp_application_logs', ['application_step'], unique=False)
    op.create_index(op.f('ix_gmp_application_logs_gmp_record_id'), 'gmp_application_logs', ['gmp_record_id'], unique=False)
    op.create_index('ix_gmp_logs_record_step', 'gmp_application_logs', ['gmp_record_id', 'application_step'], unique=False)
    op.create_table('gmp_delegation',
    sa.Column('GMP_DELEGATION_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('GMP_MAIN_ID', sa.Integer(), nullable=False),
    sa.Column('GMP_DECKER_1', sa.String(length=255), nullable=True),
    sa.Column('GMP_DECKER_1_DECISION', sa.String(length=255), nullable=True),
    sa.Column('GMP_DECKER_1_REMARKS', sa.Text(), nullable=True),
    sa.Column('GMP_DATE_DECKER_1_END', sa.DateTime(), nullable=True),
    sa.Column('GMP_QUALITY_EVALUATOR', sa.String(length=255), nullable=True),
    sa.Column('GMP_QUALITY_EVALUATOR_DECISION', sa.String(length=255), nullable=True),
    sa.Column('GMP_QUALITY_EVALUATOR_REMARKS', sa.Text(), nullable=True),
    sa.Column('GMP_DATE_QUALITY_EVALUATOR_END', sa.DateTime(), nullable=True),
    sa.Column('GMP_CHECKER', sa.String(length=255), nullable=True),
    sa.Column('GMP_CHECKER_DECISION', sa.String(length=255), nullable=True),
    sa.Column('GMP_CHECKER_REMARKS', sa.Text(), nullable=True),
    sa.Column('GMP_DATE_CHECKER_END', sa.DateTime(), nullable=True),
    sa.Column('GMP_QA_SUPERVISOR', sa.String(length=255), nullable=True),
    sa.Column('GMP_QA_SUPERVISOR_DECISION', sa.String(length=255), nullable=True),
    sa.Column('GMP_QA_SUPERVISOR_REMARKS', sa.Text(), nullable=True),
    sa.Column('GMP_DATE_QA_SUPERVISOR_END', sa.DateTime(), nullable=True),
    sa.Column('GMP_DECKER_2', sa.String(length=255), nullable=True),
    sa.Column('GMP_DECKER_2_DECISION', sa.String(length=255), nullable=True),
    sa.Column('GMP_DECKER_2_REMARKS', sa.Text(), nullable=True),
    sa.Column('GMP_DATE_DECKER_2_END', sa.DateTime(), nullable=True),
    sa.Column('GMP_LRD_CHIEF', sa.String(length=255), nullable=True),
    sa.Column('GMP_LRD_CHIEF_DECISION', sa.String(length=255), nullable=True),
    sa.Column('GMP_LRD_CHIEF_REMARKS', sa.Text(), nullable=True),
    sa.Column('GMP_DATE_LRD_CHIEF_END', sa.DateTime(), nullable=True),
    sa.Column('GMP_OD_RECEIVING', sa.String(length=255), nullable=True),
    sa.Column('GMP_OD_RECEIVING_DECISION', sa.String(length=255), nullable=True),
    sa.Column('GMP_OD_RECEIVING_REMARKS', sa.Text(), nullable=True),
    sa.Column('GMP_DATE_OD_RECEIVING_END', sa.DateTime(), nullable=True),
    sa.Column('GMP_OD_RELEASING', sa.String(length=255), nullable=True),
    sa.Column('GMP_OD_RELEASING_DECISION', sa.String(length=255), nullable=True),
    sa.Column('GMP_OD_RELEASING_REMARKS', sa.Text(), nullable=True),
    sa.Column('GMP_DATE_OD_RELEASING_END', sa.DateTime(), nullable=True),
    sa.Column('GMP_DECKER_3', sa.String(length=255), nullable=True),
    sa.Column('GMP_DECKER_3_DECISION', sa.String(length=255), nullable=True),
    sa.Column('GMP_DECKER_3_REMARKS', sa.Text(), nullable=True),
    sa.Column('GMP_DATE_DECKER_3_END', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['GMP_MAIN_ID'], ['gmp_record.GMP_ID'], ),
    sa.PrimaryKeyConstraint('GMP_DELEGATION_ID')
    )
    op.create_index(op.f('ix_gmp_delegation_GMP_MAIN_ID'), 'gmp_delegation', ['GMP_MAIN_ID'], unique=True)
    op.create_table('gmp_field_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gmp_record_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_label', sa.String(length=255), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('gmp_log_id', sa.Integer(), nullable=True),
    sa.Column('step_context', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_critical', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['gmp_log_id'], ['gmp_application_logs.id'], ),
    sa.ForeignKeyConstraint(['gmp_record_id'], ['gmp_record.GMP_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gmp_audit_record_session', 'gmp_field_audit_log', ['gmp_record_id', 'session_id'], unique=False)
    op.create_index(op.f('ix_gmp_field_audit_log_created_at'), 'gmp_field_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_gmp_field_audit_log_gmp_log_id'), 'gmp_field_audit_log', ['gmp_log_id'], unique=False)
    op.create_index(op.f('ix_gmp_field_audit_log_gmp_record_id'), 'gmp_field_audit_log', ['gmp_record_id'], unique=False)
    op.create_index(op.f('ix_gmp_field_audit_log_session_id'), 'gmp_field_audit_log', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmp_field_audit_log_session_id'), table_name='gmp_field_audit_log')
    op.drop_index(op.f('ix_gmp_field_audit_log_gmp_record_id'), table_name='gmp_field_audit_log')
    op.drop_index(op.f('ix_gmp_field_audit_log_gmp_log_id'), table_name='gmp_field_audit_log')
    op.drop_index(op.f('ix_gmp_field_audit_log_created_at'), table_name='gmp_field_audit_log')
    op.drop_index('ix_gmp_audit_record_session', table_name='gmp_field_audit_log')
    op.drop_table('gmp_field_audit_log')
    op.drop_index(op.f('ix_gmp_delegation_GMP_MAIN_ID'), table_name='gmp_delegation')
    op.drop_table('gmp_delegation')
    op.drop_index('ix_gmp_logs_record_step', table_name='gmp_application_logs')
    op.drop_index(op.f('ix_gmp_application_logs_gmp_record_id'), table_name='gmp_application_logs')
    op.drop_index(op.f('ix_gmp_application_logs_application_step'), table_name='gmp_application_logs')
    op.drop_table('gmp_application_logs')
    op.drop_index('ix_gmp_type_of_issuance', table_name='gmp_record', mysql_length=50)
    op.drop_index('ix_gmp_transaction_type', table_name='gmp_record', mysql_length=50)
    op.drop_index(op.f('ix_gmp_record_GMP_PRODUCT_LINE'), table_name='gmp_record')
    op.drop_index(op.f('ix_gmp_record_GMP_PICS_NONPICS'), table_name='gmp_record')
    op.drop_index(op.f('ix_gmp_record_GMP_ID'), table_name='gmp_record')
    op.drop_index(op.f('ix_gmp_record_GMP_EST_CATEGORY'), table_name='gmp_record')
    op.drop_index(op.f('ix_gmp_record_GMP_DTN'), table_name='gmp_record')
    op.drop_index(op.f('ix_gmp_record_GMP_DATE_EXCEL_UPLOAD'), table_name='gmp_record')
    op.drop_index(op.f('ix_gmp_record_GMP_CURRENT_STEP'), table_name='gmp_record')
    op.drop_index(op.f('ix_gmp_record_GMP_APP_STATUS'), table_name='gmp_record')
    op.drop_index('ix_gmp_lto_company', table_name='gmp_record', mysql_length=191)
    op.drop_table('gmp_record')
    # ### end Alembic commands ###
