"""Add decision authority details in main_db

Revision ID: bbc9bf306156
Revises: 8b44d21fb3dc
Create Date: 2026-04-24 05:39:37.034754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc9bf306156'
down_revision: Union[str, Sequence[str], None] = '8b44d21fb3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_db', sa.Column('DB_DECISION_AUTHORITY', sa.String(length=255), nullable=True, comment='Decision Authority Name'))
    op.add_column('main_db', sa.Column('DB_DECISION_RESULT', sa.String(length=255), nullable=True, comment='Decision Result'))
    op.add_column('main_db', sa.Column('DB_DECISION_SIGNED_DATE', sa.Date(), nullable=True, comment='Decision Authority Signed Date'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_db', 'DB_DECISION_SIGNED_DATE')
    op.drop_column('main_db', 'DB_DECISION_RESULT')
    op.drop_column('main_db', 'DB_DECISION_AUTHORITY')
    # ### end Alembic commands ###
