"""make ct_ref_no and il_approval_no nullable

Revision ID: bd20938d6891
Revises: 7a4d68d54442
Create Date: 2026-09-15 07:04:09.608158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd20938d6891'
down_revision: Union[str, Sequence[str], None] = '7a4d68d54442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinical_trials', 'ct_ref_no',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('clinical_trials', 'il_approval_no',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinical_trials', 'il_approval_no',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('clinical_trials', 'ct_ref_no',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
