"""Add bulk upload table

Revision ID: c64180b7184d
Revises: 40756cadd179
Create Date: 2026-07-07 09:32:25.210526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64180b7184d'
down_revision: Union[str, Sequence[str], None] = '40756cadd179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_upload_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('main_db_id', sa.Integer(), nullable=True),
    sa.Column('db_entry_type', sa.String(length=255), nullable=False),
    sa.Column('db_dtn', sa.String(length=255), nullable=False),
    sa.Column('doc_category', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('application_document_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_document_id'], ['application_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_upload_logs_application_document_id'), 'bulk_upload_logs', ['application_document_id'], unique=False)
    op.create_index(op.f('ix_bulk_upload_logs_batch_id'), 'bulk_upload_logs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_bulk_upload_logs_db_dtn'), 'bulk_upload_logs', ['db_dtn'], unique=False)
    op.create_index(op.f('ix_bulk_upload_logs_db_entry_type'), 'bulk_upload_logs', ['db_entry_type'], unique=False)
    op.create_index(op.f('ix_bulk_upload_logs_id'), 'bulk_upload_logs', ['id'], unique=False)
    op.create_index(op.f('ix_bulk_upload_logs_main_db_id'), 'bulk_upload_logs', ['main_db_id'], unique=False)
    op.create_index(op.f('ix_bulk_upload_logs_status'), 'bulk_upload_logs', ['status'], unique=False)
    op.create_index(op.f('ix_bulk_upload_logs_uploaded_by_user_id'), 'bulk_upload_logs', ['uploaded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bulk_upload_logs_uploaded_by_user_id'), table_name='bulk_upload_logs')
    op.drop_index(op.f('ix_bulk_upload_logs_status'), table_name='bulk_upload_logs')
    op.drop_index(op.f('ix_bulk_upload_logs_main_db_id'), table_name='bulk_upload_logs')
    op.drop_index(op.f('ix_bulk_upload_logs_id'), table_name='bulk_upload_logs')
    op.drop_index(op.f('ix_bulk_upload_logs_db_entry_type'), table_name='bulk_upload_logs')
    op.drop_index(op.f('ix_bulk_upload_logs_db_dtn'), table_name='bulk_upload_logs')
    op.drop_index(op.f('ix_bulk_upload_logs_batch_id'), table_name='bulk_upload_logs')
    op.drop_index(op.f('ix_bulk_upload_logs_application_document_id'), table_name='bulk_upload_logs')
    op.drop_table('bulk_upload_logs')
    # ### end Alembic commands ###
