"""add e_process and e_application_ref, link cpr_app_history

Revision ID: c898a7c55b1b
Revises: b45a50220706
Create Date: 2026-09-07 05:13:30.794404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c898a7c55b1b'
down_revision: Union[str, Sequence[str], None] = 'b45a50220706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e_process',
    sa.Column('process_uuid', sa.String(length=36), nullable=False),
    sa.Column('process_code', sa.String(length=50), nullable=False),
    sa.Column('process_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('process_uuid'),
    sa.UniqueConstraint('process_code')
    )
    op.create_index(op.f('ix_e_process_process_uuid'), 'e_process', ['process_uuid'], unique=False)
    op.create_table('e_application_ref',
    sa.Column('ref_uuid', sa.String(length=36), nullable=False),
    sa.Column('process_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_uuid'], ),
    sa.ForeignKeyConstraint(['process_uuid'], ['e_process.process_uuid'], ),
    sa.PrimaryKeyConstraint('ref_uuid')
    )
    op.add_column('cpr_app_history', sa.Column('process_uuid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_cpr_app_history_process_uuid'), 'cpr_app_history', ['process_uuid'], unique=False)
    op.drop_constraint(op.f('cpr_app_history_ibfk_1'), 'cpr_app_history', type_='foreignkey')
    op.create_foreign_key(None, 'cpr_app_history', 'e_application_ref', ['application_uuid'], ['ref_uuid'])
    op.create_foreign_key(None, 'cpr_app_history', 'e_process', ['process_uuid'], ['process_uuid'])
    op.drop_index(op.f('ix_cpr_application_application_uuid'), table_name='cpr_application')
    op.create_foreign_key(None, 'cpr_application', 'e_application_ref', ['application_uuid'], ['ref_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cpr_application', type_='foreignkey')
    op.create_index(op.f('ix_cpr_application_application_uuid'), 'cpr_application', ['application_uuid'], unique=False)
    op.drop_constraint(None, 'cpr_app_history', type_='foreignkey')
    op.drop_constraint(None, 'cpr_app_history', type_='foreignkey')
    op.create_foreign_key(op.f('cpr_app_history_ibfk_1'), 'cpr_app_history', 'cpr_application', ['application_uuid'], ['application_uuid'])
    op.drop_index(op.f('ix_cpr_app_history_process_uuid'), table_name='cpr_app_history')
    op.drop_column('cpr_app_history', 'process_uuid')
    op.drop_table('e_application_ref')
    op.drop_index(op.f('ix_e_process_process_uuid'), table_name='e_process')
    op.drop_table('e_process')
    # ### end Alembic commands ###
