"""add_new_cpr_tables_and_oauth_otps

Revision ID: cabcfd56e5df
Revises: d4516b1086a7
Create Date: 2026-08-24 07:17:20.884721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cabcfd56e5df"
down_revision: Union[str, Sequence[str], None] = "d4516b1086a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - manually reordered so FK targets exist first ###

    # ── 1) users.user_uuid FIRST — dependency ng cpr_app_history at oauth_otps ──
    op.add_column("users", sa.Column("user_uuid", sa.String(length=36), nullable=True))
    op.create_index(op.f("ix_users_user_uuid"), "users", ["user_uuid"], unique=True)

    # ── 2) ibang users columns (walang FK dependency, pwede kahit saan) ──
    op.add_column(
        "users", sa.Column("oauth_provider", sa.String(length=50), nullable=True)
    )
    op.add_column("users", sa.Column("oauth_sub", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_users_oauth_sub"), "users", ["oauth_sub"], unique=True)

    # ── 3) cpr_application (walang FK dependency sa users) ──
    op.create_table(
        "cpr_application",
        sa.Column("application_uuid", sa.String(length=36), nullable=False),
        sa.Column("reference_number", sa.String(length=255), nullable=True),
        sa.Column("activity", sa.String(length=255), nullable=True),
        sa.Column("applicant_company", sa.String(length=255), nullable=True),
        sa.Column("email_address", sa.String(length=255), nullable=True),
        sa.Column("contact_no", sa.String(length=50), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("tin", sa.String(length=50), nullable=True),
        sa.Column("lto_no", sa.String(length=100), nullable=True),
        sa.Column("validity", sa.String(length=100), nullable=True),
        sa.Column("application_type", sa.String(length=100), nullable=True),
        sa.Column("brand_name", sa.String(length=255), nullable=True),
        sa.Column("generic_name", sa.String(length=255), nullable=True),
        sa.Column("dosage_strength", sa.String(length=255), nullable=True),
        sa.Column("dosage_form_route", sa.String(length=255), nullable=True),
        sa.Column("classification", sa.String(length=255), nullable=True),
        sa.Column("product_category", sa.String(length=255), nullable=True),
        sa.Column("essential_drug_list", sa.String(length=255), nullable=True),
        sa.Column("pharmacologic_category", sa.String(length=255), nullable=True),
        sa.Column("shelf_life", sa.String(length=255), nullable=True),
        sa.Column("storage_condition", sa.String(length=255), nullable=True),
        sa.Column("packaging", sa.String(length=255), nullable=True),
        sa.Column("suggested_retail_price", sa.String(length=100), nullable=True),
        sa.Column("registration_number", sa.String(length=100), nullable=True),
        sa.Column("mother_application_type", sa.String(length=100), nullable=True),
        sa.Column("old_rsn_other_dtn", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("application_uuid"),
    )
    op.create_index(
        op.f("ix_cpr_application_application_uuid"),
        "cpr_application",
        ["application_uuid"],
        unique=False,
    )

    # ── 4) cpr_app_history (FK -> cpr_application, users.user_uuid) ──
    op.create_table(
        "cpr_app_history",
        sa.Column("history_uuid", sa.String(length=36), nullable=False),
        sa.Column("application_uuid", sa.String(length=36), nullable=False),
        sa.Column("reference_number", sa.String(length=255), nullable=True),
        sa.Column("user_uuid", sa.String(length=36), nullable=True),
        sa.Column("application_step", sa.String(length=255), nullable=True),
        sa.Column("application_status", sa.String(length=255), nullable=True),
        sa.Column("application_decision", sa.String(length=255), nullable=True),
        sa.Column("application_remarks", sa.Text(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("accomplished_date", sa.DateTime(), nullable=True),
        sa.Column("step_duedate", sa.String(length=100), nullable=True),
        sa.Column("deadline_date", sa.Date(), nullable=True),
        sa.Column("working_days", sa.SmallInteger(), nullable=True),
        sa.Column("is_read", sa.SmallInteger(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("is_received", sa.SmallInteger(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=True),
        sa.Column("received_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("del_index", sa.Integer(), nullable=True),
        sa.Column("del_previous", sa.Integer(), nullable=True),
        sa.Column("del_last_index", sa.Integer(), nullable=True),
        sa.Column("del_thread", sa.String(length=60), nullable=True),
        sa.Column("reassigned_by_user_uuid", sa.String(length=36), nullable=True),
        sa.Column("reassigned_at", sa.DateTime(), nullable=True),
        sa.Column("reassigned_from_user_uuid", sa.String(length=36), nullable=True),
        sa.Column("reassigned_to_user_uuid", sa.String(length=36), nullable=True),
        sa.Column("reassignment_reason", sa.String(length=255), nullable=True),
        sa.Column("reassignment_remarks", sa.Text(), nullable=True),
        sa.Column("rerouted_by_user_uuid", sa.String(length=36), nullable=True),
        sa.Column("rerouted_at", sa.DateTime(), nullable=True),
        sa.Column("reroute_from_step", sa.String(length=255), nullable=True),
        sa.Column("reroute_target_step", sa.String(length=255), nullable=True),
        sa.Column("reroute_reason", sa.String(length=255), nullable=True),
        sa.Column("reroute_remarks", sa.Text(), nullable=True),
        sa.Column("is_starred", sa.SmallInteger(), nullable=False),
        sa.Column("starred_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_uuid"],
            ["cpr_application.application_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["reassigned_by_user_uuid"],
            ["users.user_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["reassigned_from_user_uuid"],
            ["users.user_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["reassigned_to_user_uuid"],
            ["users.user_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["rerouted_by_user_uuid"],
            ["users.user_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("history_uuid"),
    )
    op.create_index(
        op.f("ix_cpr_app_history_application_status"),
        "cpr_app_history",
        ["application_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cpr_app_history_deadline_date"),
        "cpr_app_history",
        ["deadline_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cpr_app_history_del_thread"),
        "cpr_app_history",
        ["del_thread"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cpr_app_history_history_uuid"),
        "cpr_app_history",
        ["history_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cpr_app_history_user_uuid"),
        "cpr_app_history",
        ["user_uuid"],
        unique=False,
    )

    # ── 5) cpr_app_parties (FK -> cpr_application lang) ──
    op.create_table(
        "cpr_app_parties",
        sa.Column("party_uuid", sa.String(length=36), nullable=False),
        sa.Column("application_uuid", sa.String(length=36), nullable=False),
        sa.Column("party_type", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("tin", sa.String(length=50), nullable=True),
        sa.Column("lto_no", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_uuid"],
            ["cpr_application.application_uuid"],
        ),
        sa.PrimaryKeyConstraint("party_uuid"),
    )
    op.create_index(
        op.f("ix_cpr_app_parties_party_uuid"),
        "cpr_app_parties",
        ["party_uuid"],
        unique=False,
    )

    # ── 6) oauth_otps (FK -> users.user_uuid) ──
    op.create_table(
        "oauth_otps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_uuid", sa.String(length=36), nullable=False),
        sa.Column("otp_hash", sa.String(length=255), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("consumed", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_oauth_otps_id"), "oauth_otps", ["id"], unique=False)
    op.create_index(
        op.f("ix_oauth_otps_user_uuid"), "oauth_otps", ["user_uuid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ── reverse of 6) oauth_otps ──
    op.drop_table("oauth_otps")  # tinanggal na ang 2 drop_index lines bago nito

    # ── reverse of 5) cpr_app_parties ──
    op.drop_index(op.f("ix_cpr_app_parties_party_uuid"), table_name="cpr_app_parties")
    op.drop_table("cpr_app_parties")

    # ── reverse of 4) cpr_app_history ──
    op.drop_table(
        "cpr_app_history"
    )  # tinanggal na rin lahat ng drop_index lines bago nito

    # ── reverse of 3) cpr_application ──
    op.drop_index(
        op.f("ix_cpr_application_application_uuid"), table_name="cpr_application"
    )
    op.drop_table("cpr_application")

    # ── reverse of 2) ibang users columns ──
    op.drop_index(op.f("ix_users_oauth_sub"), table_name="users")
    op.drop_column("users", "oauth_sub")
    op.drop_column("users", "oauth_provider")

    # ── reverse of 1) users.user_uuid ──
    op.drop_index(op.f("ix_users_user_uuid"), table_name="users")
    op.drop_column("users", "user_uuid")
