"""add new column in cpr history

Revision ID: d2d94da241e0
Revises: c898a7c55b1b
Create Date: 2026-09-08 05:16:04.844389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d94da241e0'
down_revision: Union[str, Sequence[str], None] = 'c898a7c55b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpr_app_history', sa.Column('priority', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cpr_app_history', 'priority')
    # ### end Alembic commands ###
