"""Add DB_TIMELINE_CITIZEN_CHARTER to main_db

Revision ID: d62e7917dfc6
Revises: f03b85465203
Create Date: 2026-01-26 05:12:01.620720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62e7917dfc6'
down_revision: Union[str, Sequence[str], None] = 'f03b85465203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_db', sa.Column('DB_TIMELINE_CITIZEN_CHARTER', sa.Integer(), nullable=True, comment='Timeline for Citizen Charter'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_db', 'DB_TIMELINE_CITIZEN_CHARTER')
    # ### end Alembic commands ###
