"""new table for generated dopcument

Revision ID: df0cdce6c2f6
Revises: 2da1d9919873
Create Date: 2026-09-23 05:55:47.787244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'df0cdce6c2f6'
down_revision: Union[str, Sequence[str], None] = '2da1d9919873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_trial_drugs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinical_trial_id', sa.Integer(), nullable=False),
    sa.Column('ip_name', sa.Text(), nullable=True),
    sa.Column('dosage_strength', sa.String(length=100), nullable=True),
    sa.Column('pharma_form', sa.String(length=100), nullable=True),
    sa.Column('drug_type', sa.Text(), nullable=True),
    sa.Column('total_qty_approve', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinical_trial_id'], ['clinical_trials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_trial_drugs_clinical_trial_id'), 'clinical_trial_drugs', ['clinical_trial_id'], unique=False)
    op.drop_column('clinical_trials', 'pharma_form')
    op.drop_column('clinical_trials', 'dosage_strength')
    op.drop_column('clinical_trials', 'total_qty_approve')
    op.drop_column('clinical_trials', 'drug_type')
    op.drop_column('clinical_trials', 'ip_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_trials', sa.Column('ip_name', mysql.TEXT(), nullable=True))
    op.add_column('clinical_trials', sa.Column('drug_type', mysql.TEXT(), nullable=True))
    op.add_column('clinical_trials', sa.Column('total_qty_approve', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('clinical_trials', sa.Column('dosage_strength', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('clinical_trials', sa.Column('pharma_form', mysql.VARCHAR(length=100), nullable=True))
    op.drop_index(op.f('ix_clinical_trial_drugs_clinical_trial_id'), table_name='clinical_trial_drugs')
    op.drop_table('clinical_trial_drugs')
    # ### end Alembic commands ###
