"""add gmp logs extended fields

Revision ID: e675fa62c950
Revises: baeecbcab1cc
Create Date: 2026-07-07 07:05:47.348404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e675fa62c950'
down_revision: Union[str, Sequence[str], None] = 'baeecbcab1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmp_application_logs', sa.Column('action_type', sa.String(length=100), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('decision_result', sa.String(length=255), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('decision_authority_id', sa.Integer(), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('decision_authority_name', sa.String(length=255), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('doctrack_remarks', sa.Text(), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('deadline_date', sa.DateTime(), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('working_days', sa.Integer(), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('reassigned_by_user_id', sa.Integer(), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('reassigned_by_user_name', sa.String(length=255), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('reassigned_at', sa.DateTime(), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('reassigned_from_user_id', sa.Integer(), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('reassigned_from_user_name', sa.String(length=255), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('reassigned_to_user_id', sa.Integer(), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('reassigned_to_user_name', sa.String(length=255), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('reassignment_reason', sa.String(length=255), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('reassignment_remarks', sa.Text(), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('rerouted_by_user_id', sa.Integer(), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('rerouted_by_user_name', sa.String(length=255), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('rerouted_at', sa.DateTime(), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('reroute_from_step', sa.String(length=100), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('reroute_target_step', sa.String(length=100), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('reroute_reason', sa.String(length=255), nullable=True))
    op.add_column('gmp_application_logs', sa.Column('reroute_remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmp_application_logs', 'reroute_remarks')
    op.drop_column('gmp_application_logs', 'reroute_reason')
    op.drop_column('gmp_application_logs', 'reroute_target_step')
    op.drop_column('gmp_application_logs', 'reroute_from_step')
    op.drop_column('gmp_application_logs', 'rerouted_at')
    op.drop_column('gmp_application_logs', 'rerouted_by_user_name')
    op.drop_column('gmp_application_logs', 'rerouted_by_user_id')
    op.drop_column('gmp_application_logs', 'reassignment_remarks')
    op.drop_column('gmp_application_logs', 'reassignment_reason')
    op.drop_column('gmp_application_logs', 'reassigned_to_user_name')
    op.drop_column('gmp_application_logs', 'reassigned_to_user_id')
    op.drop_column('gmp_application_logs', 'reassigned_from_user_name')
    op.drop_column('gmp_application_logs', 'reassigned_from_user_id')
    op.drop_column('gmp_application_logs', 'reassigned_at')
    op.drop_column('gmp_application_logs', 'reassigned_by_user_name')
    op.drop_column('gmp_application_logs', 'reassigned_by_user_id')
    op.drop_column('gmp_application_logs', 'working_days')
    op.drop_column('gmp_application_logs', 'deadline_date')
    op.drop_column('gmp_application_logs', 'doctrack_remarks')
    op.drop_column('gmp_application_logs', 'decision_authority_name')
    op.drop_column('gmp_application_logs', 'decision_authority_id')
    op.drop_column('gmp_application_logs', 'decision_result')
    op.drop_column('gmp_application_logs', 'action_type')
    # ### end Alembic commands ###
