"""Add new table Application_logs

Revision ID: ed90153df997
Revises: 1900dd56f6fb
Create Date: 2026-01-12 15:58:35.615462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed90153df997'
down_revision: Union[str, Sequence[str], None] = '1900dd56f6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    'application_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_step', sa.String(length=255), nullable=True, comment='Current Application Step'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User ID Processing the Application'),
    sa.Column('application_status', sa.String(length=255), nullable=True, index=True, comment='Application Status'),
    sa.Column('application_decision', sa.String(length=255), nullable=True, comment='Application Decision'),
    sa.Column('application_remarks', sa.Text(), nullable=True, comment='Application Remarks'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='Start Date'),
    sa.Column('accomplished_date', sa.DateTime(), nullable=True, comment='Accomplished Date'),
    sa.Column('main_db_dtn', sa.BigInteger(), nullable=False, comment='Foreign Key - DTN from MainDB'),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now(), comment='Record Created At'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now(), onupdate=sa.func.now(), comment='Record Updated At'),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['main_db_dtn'], ['main_db.DB_DTN'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL')
    )
    op.create_index('ix_application_logs_application_status', 'application_logs', ['application_status'], unique=False)
    op.create_index('ix_application_logs_main_db_dtn', 'application_logs', ['main_db_dtn'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_logs_main_db_dtn'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_id'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_application_status'), table_name='application_logs')
    op.drop_table('application_logs')
    # ### end Alembic commands ###
