"""Add new column in application delegation Releasing Officer

Revision ID: f03b85465203
Revises: 992c33bb65c1
Create Date: 2026-01-19 09:30:49.042450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03b85465203'
down_revision: Union[str, Sequence[str], None] = '992c33bb65c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_delegation', sa.Column('DB_RELEASING_OFFICER', sa.Text(), nullable=True, comment='Releasing Officer Name'))
    op.add_column('application_delegation', sa.Column('DB_RELEASING_OFFICER_DECISION', sa.Text(), nullable=True, comment='Releasing Officer Decision'))
    op.add_column('application_delegation', sa.Column('DB_RELEASING_OFFICER_REMARKS', sa.Text(), nullable=True, comment='Releasing Officer Remarks'))
    op.add_column('application_delegation', sa.Column('DB_RELEASING_OFFICER_END', sa.DateTime(), nullable=True, comment='Date Releasing Officer End'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_delegation', 'DB_RELEASING_OFFICER_END')
    op.drop_column('application_delegation', 'DB_RELEASING_OFFICER_REMARKS')
    op.drop_column('application_delegation', 'DB_RELEASING_OFFICER_DECISION')
    op.drop_column('application_delegation', 'DB_RELEASING_OFFICER')
    # ### end Alembic commands ###
