"""Add entry type in main_db

Revision ID: f088d6f232f8
Revises: 2e1ded56fbc4
Create Date: 2026-05-25 05:24:47.594279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f088d6f232f8'
down_revision: Union[str, Sequence[str], None] = '2e1ded56fbc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_db', sa.Column('DB_ENTRY_TYPE', sa.String(length=50), nullable=True, comment='Entry Type: ORIGINAL, CORRECTION, RECONSTRUCTION'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_db', 'DB_ENTRY_TYPE')
    # ### end Alembic commands ###
