"""Update app delegation table

Revision ID: f6d41b7d72dc
Revises: c4cc96518876
Create Date: 2026-02-09 05:58:36.477938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6d41b7d72dc'
down_revision: Union[str, Sequence[str], None] = 'c4cc96518876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_delegation', 'DB_DATE_DECKED_END',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Date Decked End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_EVAL_END',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Date Evaluation End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_CHECKER_END',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Date Checker End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_SUPERVISOR_END',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Date Supervisor End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_QA_END',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Date QA End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_DIRECTOR_END',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Date Director End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_RELEASING_OFFICER_END',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Date Releasing Officer End',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_delegation', 'DB_RELEASING_OFFICER_END',
               existing_type=mysql.DATETIME(),
               comment='Date Releasing Officer End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_DIRECTOR_END',
               existing_type=mysql.DATETIME(),
               comment='Date Director End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_QA_END',
               existing_type=mysql.DATETIME(),
               comment='Date QA End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_SUPERVISOR_END',
               existing_type=mysql.DATETIME(),
               comment='Date Supervisor End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_CHECKER_END',
               existing_type=mysql.DATETIME(),
               comment='Date Checker End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_EVAL_END',
               existing_type=mysql.DATETIME(),
               comment='Date Evaluation End',
               existing_nullable=True)
    op.alter_column('application_delegation', 'DB_DATE_DECKED_END',
               existing_type=mysql.DATETIME(),
               comment='Date Decked End',
               existing_nullable=True)
    # ### end Alembic commands ###
