"""Update model for target assignments

Revision ID: fe7c06bcd3be
Revises: 559e3361eba3
Create Date: 2026-07-14 02:46:57.617498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7c06bcd3be'
down_revision: Union[str, Sequence[str], None] = '559e3361eba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_assignments', sa.Column('target_start_date', sa.Date(), nullable=True))
    op.add_column('target_assignments', sa.Column('target_end_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_target_assignments_target_end_date'), 'target_assignments', ['target_end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_assignments_target_end_date'), table_name='target_assignments')
    op.drop_column('target_assignments', 'target_end_date')
    op.drop_column('target_assignments', 'target_start_date')
    # ### end Alembic commands ###
