"""add gmp sent_by_full_name field

Revision ID: ffcfbc5aacbc
Revises: 585c63bc9b92
Create Date: 2026-07-15 05:07:52.739728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffcfbc5aacbc'
down_revision: Union[str, Sequence[str], None] = '585c63bc9b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmp_application_logs', sa.Column('sent_by_full_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmp_application_logs', 'sent_by_full_name')
    # ### end Alembic commands ###
